// ~Hack~ Pokemon Unbound [Subset - Professor Oak Challenge]
// #ID = 24224

pokedex = {
    "Bulbasaur":bit0(0x02d8b9),
    "Ivysaur":bit1(0x02d8b9),
    "Venusaur":bit2(0x02d8b9),
    "Charmander":bit3(0x02d8b9),
    "Charmeleon":bit4(0x02d8b9),
    "Charizard":bit5(0x02d8b9),
    "Squirtle":bit6(0x02d8b9),
    "Wartortle":bit7(0x02d8b9),
    "Blastoise":bit0(0x02d8ba),
    "Caterpie":bit1(0x02d8ba),
    "Metapod":bit2(0x02d8ba),
    "Butterfree":bit3(0x02d8ba),
    "Weedle":bit4(0x02d8ba),
    "Kakuna":bit5(0x02d8ba),
    "Beedrill":bit6(0x02d8ba),
    "Pidgey":bit7(0x02d8ba),
    "Pidgeotto":bit0(0x02d8bb),
    "Pidgeot":bit1(0x02d8bb),
    "Rattata":bit2(0x02d8bb),
    "Raticate":bit3(0x02d8bb),
    "Spearow":bit4(0x02d8bb),
    "Fearow":bit5(0x02d8bb),
    "Ekans":bit6(0x02d8bb),
    "Arbok":bit7(0x02d8bb),
    "Pikachu":bit0(0x02d8bc),
    "Raichu":bit1(0x02d8bc),
    "Sandshrew":bit2(0x02d8bc),
    "Sandslash":bit3(0x02d8bc),
    "Nidoran♀":bit4(0x02d8bc),
    "Nidorina":bit5(0x02d8bc),
    "Nidoqueen":bit6(0x02d8bc),
    "Nidoran♂":bit7(0x02d8bc),
    "Nidorino":bit0(0x02d8bd),
    "Nidoking":bit1(0x02d8bd),
    "Clefairy":bit2(0x02d8bd),
    "Clefable":bit3(0x02d8bd),
    "Vulpix":bit4(0x02d8bd),
    "Ninetales":bit5(0x02d8bd),
    "Jigglypuff":bit6(0x02d8bd),
    "Wigglytuff":bit7(0x02d8bd),
    "Zubat":bit0(0x02d8be),
    "Golbat":bit1(0x02d8be),
    "Oddish":bit2(0x02d8be),
    "Gloom":bit3(0x02d8be),
    "Vileplume":bit4(0x02d8be),
    "Paras":bit5(0x02d8be),
    "Parasect":bit6(0x02d8be),
    "Venonat":bit7(0x02d8be),
    "Venomoth":bit0(0x02d8bf),
    "Diglett":bit1(0x02d8bf),
    "Dugtrio":bit2(0x02d8bf),
    "Meowth":bit3(0x02d8bf),
    "Persian":bit4(0x02d8bf),
    "Psyduck":bit5(0x02d8bf),
    "Golduck":bit6(0x02d8bf),
    "Mankey":bit7(0x02d8bf),
    "Primeape":bit0(0x02d8c0),
    "Growlithe":bit1(0x02d8c0),
    "Arcanine":bit2(0x02d8c0),
    "Poliwag":bit3(0x02d8c0),
    "Poliwhirl":bit4(0x02d8c0),
    "Poliwrath":bit5(0x02d8c0),
    "Abra":bit6(0x02d8c0),
    "Kadabra":bit7(0x02d8c0),
    "Alakazam":bit0(0x02d8c1),
    "Machop":bit1(0x02d8c1),
    "Machoke":bit2(0x02d8c1),
    "Machamp":bit3(0x02d8c1),
    "Bellsprout":bit4(0x02d8c1),
    "Weepinbell":bit5(0x02d8c1),
    "Victreebel":bit6(0x02d8c1),
    "Tentacool":bit7(0x02d8c1),
    "Tentacruel":bit0(0x02d8c2),
    "Geodude":bit1(0x02d8c2),
    "Graveler":bit2(0x02d8c2),
    "Golem":bit3(0x02d8c2),
    "Ponyta":bit4(0x02d8c2),
    "Rapidash":bit5(0x02d8c2),
    "Slowpoke":bit6(0x02d8c2),
    "Slowbro":bit7(0x02d8c2),
    "Magnemite":bit0(0x02d8c3),
    "Magneton":bit1(0x02d8c3),
    "Farfetch'd":bit2(0x02d8c3),
    "Doduo":bit3(0x02d8c3),
    "Dodrio":bit4(0x02d8c3),
    "Seel":bit5(0x02d8c3),
    "Dewgong":bit6(0x02d8c3),
    "Grimer":bit7(0x02d8c3),
    "Muk":bit0(0x02d8c4),
    "Shellder":bit1(0x02d8c4),
    "Cloyster":bit2(0x02d8c4),
    "Gastly":bit3(0x02d8c4),
    "Haunter":bit4(0x02d8c4),
    "Gengar":bit5(0x02d8c4),
    "Onix":bit6(0x02d8c4),
    "Drowzee":bit7(0x02d8c4),
    "Hypno":bit0(0x02d8c5),
    "Krabby":bit1(0x02d8c5),
    "Kingler":bit2(0x02d8c5),
    "Voltorb":bit3(0x02d8c5),
    "Electrode":bit4(0x02d8c5),
    "Exeggcute":bit5(0x02d8c5),
    "Exeggutor":bit6(0x02d8c5),
    "Cubone":bit7(0x02d8c5),
    "Marowak":bit0(0x02d8c6),
    "Hitmonlee":bit1(0x02d8c6),
    "Hitmonchan":bit2(0x02d8c6),
    "Lickitung":bit3(0x02d8c6),
    "Koffing":bit4(0x02d8c6),
    "Weezing":bit5(0x02d8c6),
    "Rhyhorn":bit6(0x02d8c6),
    "Rhydon":bit7(0x02d8c6),
    "Chansey":bit0(0x02d8c7),
    "Tangela":bit1(0x02d8c7),
    "Kangaskhan":bit2(0x02d8c7),
    "Horsea":bit3(0x02d8c7),
    "Seadra":bit4(0x02d8c7),
    "Goldeen":bit5(0x02d8c7),
    "Seaking":bit6(0x02d8c7),
    "Staryu":bit7(0x02d8c7),
    "Starmie":bit0(0x02d8c8),
    "Mr. Mime":bit1(0x02d8c8),
    "Scyther":bit2(0x02d8c8),
    "Jynx":bit3(0x02d8c8),
    "Electabuzz":bit4(0x02d8c8),
    "Magmar":bit5(0x02d8c8),
    "Pinsir":bit6(0x02d8c8),
    "Tauros":bit7(0x02d8c8),
    "Magikarp":bit0(0x02d8c9),
    "Gyarados":bit1(0x02d8c9),
    "Lapras":bit2(0x02d8c9),
    "Ditto":bit3(0x02d8c9),
    "Eevee":bit4(0x02d8c9),
    "Vaporeon":bit5(0x02d8c9),
    "Jolteon":bit6(0x02d8c9),
    "Flareon":bit7(0x02d8c9),
    "Porygon":bit0(0x02d8ca),
    "Omanyte":bit1(0x02d8ca),
    "Omastar":bit2(0x02d8ca),
    "Kabuto":bit3(0x02d8ca),
    "Kabutops":bit4(0x02d8ca),
    "Aerodactyl":bit5(0x02d8ca),
    "Snorlax":bit6(0x02d8ca),
    "Articuno":bit7(0x02d8ca),
    "Zapdos":bit0(0x02d8cb),
    "Moltres":bit1(0x02d8cb),
    "Dratini":bit2(0x02d8cb),
    "Dragonair":bit3(0x02d8cb),
    "Dragonite":bit4(0x02d8cb),
    "Mewtwo":bit5(0x02d8cb),
    "Mew":bit6(0x02d8cb),
    "Chikorita":bit7(0x02d8cb),
    "Bayleef":bit0(0x02d8cc),
    "Meganium":bit1(0x02d8cc),
    "Cyndaquil":bit2(0x02d8cc),
    "Quilava":bit3(0x02d8cc),
    "Typhlosion":bit4(0x02d8cc),
    "Totodile":bit5(0x02d8cc),
    "Croconaw":bit6(0x02d8cc),
    "Feraligatr":bit7(0x02d8cc),
    "Sentret":bit0(0x02d8cd),
    "Furret":bit1(0x02d8cd),
    "Hoothoot":bit2(0x02d8cd),
    "Noctowl":bit3(0x02d8cd),
    "Ledyba":bit4(0x02d8cd),
    "Ledian":bit5(0x02d8cd),
    "Spinarak":bit6(0x02d8cd),
    "Ariados":bit7(0x02d8cd),
    "Crobat":bit0(0x02d8ce),
    "Chinchou":bit1(0x02d8ce),
    "Lanturn":bit2(0x02d8ce),
    "Pichu":bit3(0x02d8ce),
    "Cleffa":bit4(0x02d8ce),
    "Igglybuff":bit5(0x02d8ce),
    "Togepi":bit6(0x02d8ce),
    "Togetic":bit7(0x02d8ce),
    "Natu":bit0(0x02d8cf),
    "Xatu":bit1(0x02d8cf),
    "Mareep":bit2(0x02d8cf),
    "Flaaffy":bit3(0x02d8cf),
    "Ampharos":bit4(0x02d8cf),
    "Bellossom":bit5(0x02d8cf),
    "Marill":bit6(0x02d8cf),
    "Azumarill":bit7(0x02d8cf),
    "Sudowoodo":bit0(0x02d8d0),
    "Politoed":bit1(0x02d8d0),
    "Hoppip":bit2(0x02d8d0),
    "Skiploom":bit3(0x02d8d0),
    "Jumpluff":bit4(0x02d8d0),
    "Aipom":bit5(0x02d8d0),
    "Sunkern":bit6(0x02d8d0),
    "Sunflora":bit7(0x02d8d0),
    "Yanma":bit0(0x02d8d1),
    "Wooper":bit1(0x02d8d1),
    "Quagsire":bit2(0x02d8d1),
    "Espeon":bit3(0x02d8d1),
    "Umbreon":bit4(0x02d8d1),
    "Murkrow":bit5(0x02d8d1),
    "Slowking":bit6(0x02d8d1),
    "Misdreavus":bit7(0x02d8d1),
    "Unown":bit0(0x02d8d2),
    "Wobbuffet":bit1(0x02d8d2),
    "Girafarig":bit2(0x02d8d2),
    "Pineco":bit3(0x02d8d2),
    "Forretress":bit4(0x02d8d2),
    "Dunsparce":bit5(0x02d8d2),
    "Gligar":bit6(0x02d8d2),
    "Steelix":bit7(0x02d8d2),
    "Snubbull":bit0(0x02d8d3),
    "Granbull":bit1(0x02d8d3),
    "Qwilfish":bit2(0x02d8d3),
    "Scizor":bit3(0x02d8d3),
    "Shuckle":bit4(0x02d8d3),
    "Heracross":bit5(0x02d8d3),
    "Sneasel":bit6(0x02d8d3),
    "Teddiursa":bit7(0x02d8d3),
    "Ursaring":bit0(0x02d8d4),
    "Slugma":bit1(0x02d8d4),
    "Magcargo":bit2(0x02d8d4),
    "Swinub":bit3(0x02d8d4),
    "Piloswine":bit4(0x02d8d4),
    "Corsola":bit5(0x02d8d4),
    "Remoraid":bit6(0x02d8d4),
    "Octillery":bit7(0x02d8d4),
    "Delibird":bit0(0x02d8d5),
    "Mantine":bit1(0x02d8d5),
    "Skarmory":bit2(0x02d8d5),
    "Houndour":bit3(0x02d8d5),
    "Houndoom":bit4(0x02d8d5),
    "Kingdra":bit5(0x02d8d5),
    "Phanpy":bit6(0x02d8d5),
    "Donphan":bit7(0x02d8d5),
    "Porygon2":bit0(0x02d8d6),
    "Stantler":bit1(0x02d8d6),
    "Smeargle":bit2(0x02d8d6),
    "Tyrogue":bit3(0x02d8d6),
    "Hitmontop":bit4(0x02d8d6),
    "Smoochum":bit5(0x02d8d6),
    "Elekid":bit6(0x02d8d6),
    "Magby":bit7(0x02d8d6),
    "Miltank":bit0(0x02d8d7),
    "Blissey":bit1(0x02d8d7),
    "Raikou":bit2(0x02d8d7),
    "Entei":bit3(0x02d8d7),
    "Suicune":bit4(0x02d8d7),
    "Larvitar":bit5(0x02d8d7),
    "Pupitar":bit6(0x02d8d7),
    "Tyranitar":bit7(0x02d8d7),
    "Lugia":bit0(0x02d8d8),
    "Ho-Oh":bit1(0x02d8d8),
    "Celebi":bit2(0x02d8d8),
    "Treecko":bit3(0x02d8d8),
    "Grovyle":bit4(0x02d8d8),
    "Sceptile":bit5(0x02d8d8),
    "Torchic":bit6(0x02d8d8),
    "Combusken":bit7(0x02d8d8),
    "Blaziken":bit0(0x02d8d9),
    "Mudkip":bit1(0x02d8d9),
    "Marshtomp":bit2(0x02d8d9),
    "Swampert":bit3(0x02d8d9),
    "Poochyena":bit4(0x02d8d9),
    "Mightyena":bit5(0x02d8d9),
    "Zigzagoon":bit6(0x02d8d9),
    "Linoone":bit7(0x02d8d9),
    "Wurmple":bit0(0x02d8da),
    "Silcoon":bit1(0x02d8da),
    "Beautifly":bit2(0x02d8da),
    "Cascoon":bit3(0x02d8da),
    "Dustox":bit4(0x02d8da),
    "Lotad":bit5(0x02d8da),
    "Lombre":bit6(0x02d8da),
    "Ludicolo":bit7(0x02d8da),
    "Seedot":bit0(0x02d8db),
    "Nuzleaf":bit1(0x02d8db),
    "Shiftry":bit2(0x02d8db),
    "Taillow":bit3(0x02d8db),
    "Swellow":bit4(0x02d8db),
    "Wingull":bit5(0x02d8db),
    "Pelipper":bit6(0x02d8db),
    "Ralts":bit7(0x02d8db),
    "Kirlia":bit0(0x02d8dc),
    "Gardevoir":bit1(0x02d8dc),
    "Surskit":bit2(0x02d8dc),
    "Masquerain":bit3(0x02d8dc),
    "Shroomish":bit4(0x02d8dc),
    "Breloom":bit5(0x02d8dc),
    "Slakoth":bit6(0x02d8dc),
    "Vigoroth":bit7(0x02d8dc),
    "Slaking":bit0(0x02d8dd),
    "Nincada":bit1(0x02d8dd),
    "Ninjask":bit2(0x02d8dd),
    "Shedinja":bit3(0x02d8dd),
    "Whismur":bit4(0x02d8dd),
    "Loudred":bit5(0x02d8dd),
    "Exploud":bit6(0x02d8dd),
    "Makuhita":bit7(0x02d8dd),
    "Hariyama":bit0(0x02d8de),
    "Azurill":bit1(0x02d8de),
    "Nosepass":bit2(0x02d8de),
    "Skitty":bit3(0x02d8de),
    "Delcatty":bit4(0x02d8de),
    "Sableye":bit5(0x02d8de),
    "Mawile":bit6(0x02d8de),
    "Aron":bit7(0x02d8de),
    "Lairon":bit0(0x02d8df),
    "Aggron":bit1(0x02d8df),
    "Meditite":bit2(0x02d8df),
    "Medicham":bit3(0x02d8df),
    "Electrike":bit4(0x02d8df),
    "Manectric":bit5(0x02d8df),
    "Plusle":bit6(0x02d8df),
    "Minun":bit7(0x02d8df),
    "Volbeat":bit0(0x02d8e0),
    "Illumise":bit1(0x02d8e0),
    "Roselia":bit2(0x02d8e0),
    "Gulpin":bit3(0x02d8e0),
    "Swalot":bit4(0x02d8e0),
    "Carvanha":bit5(0x02d8e0),
    "Sharpedo":bit6(0x02d8e0),
    "Wailmer":bit7(0x02d8e0),
    "Wailord":bit0(0x02d8e1),
    "Numel":bit1(0x02d8e1),
    "Camerupt":bit2(0x02d8e1),
    "Torkoal":bit3(0x02d8e1),
    "Spoink":bit4(0x02d8e1),
    "Grumpig":bit5(0x02d8e1),
    "Spinda":bit6(0x02d8e1),
    "Trapinch":bit7(0x02d8e1),
    "Vibrava":bit0(0x02d8e2),
    "Flygon":bit1(0x02d8e2),
    "Cacnea":bit2(0x02d8e2),
    "Cacturne":bit3(0x02d8e2),
    "Swablu":bit4(0x02d8e2),
    "Altaria":bit5(0x02d8e2),
    "Zangoose":bit6(0x02d8e2),
    "Seviper":bit7(0x02d8e2),
    "Lunatone":bit0(0x02d8e3),
    "Solrock":bit1(0x02d8e3),
    "Barboach":bit2(0x02d8e3),
    "Whiscash":bit3(0x02d8e3),
    "Corphish":bit4(0x02d8e3),
    "Crawdaunt":bit5(0x02d8e3),
    "Baltoy":bit6(0x02d8e3),
    "Claydol":bit7(0x02d8e3),
    "Lileep":bit0(0x02d8e4),
    "Cradily":bit1(0x02d8e4),
    "Anorith":bit2(0x02d8e4),
    "Armaldo":bit3(0x02d8e4),
    "Feebas":bit4(0x02d8e4),
    "Milotic":bit5(0x02d8e4),
    "Castform":bit6(0x02d8e4),
    "Kecleon":bit7(0x02d8e4),
    "Shuppet":bit0(0x02d8e5),
    "Banette":bit1(0x02d8e5),
    "Duskull":bit2(0x02d8e5),
    "Dusclops":bit3(0x02d8e5),
    "Tropius":bit4(0x02d8e5),
    "Chimecho":bit5(0x02d8e5),
    "Absol":bit6(0x02d8e5),
    "Wynaut":bit7(0x02d8e5),
    "Snorunt":bit0(0x02d8e6),
    "Glalie":bit1(0x02d8e6),
    "Spheal":bit2(0x02d8e6),
    "Sealeo":bit3(0x02d8e6),
    "Walrein":bit4(0x02d8e6),
    "Clamperl":bit5(0x02d8e6),
    "Huntail":bit6(0x02d8e6),
    "Gorebyss":bit7(0x02d8e6),
    "Relicanth":bit0(0x02d8e7),
    "Luvdisc":bit1(0x02d8e7),
    "Bagon":bit2(0x02d8e7),
    "Shelgon":bit3(0x02d8e7),
    "Salamence":bit4(0x02d8e7),
    "Beldum":bit5(0x02d8e7),
    "Metang":bit6(0x02d8e7),
    "Metagross":bit7(0x02d8e7),
    "Regirock":bit0(0x02d8e8),
    "Regice":bit1(0x02d8e8),
    "Registeel":bit2(0x02d8e8),
    "Latias":bit3(0x02d8e8),
    "Latios":bit4(0x02d8e8),
    "Kyogre":bit5(0x02d8e8),
    "Groudon":bit6(0x02d8e8),
    "Rayquaza":bit7(0x02d8e8),
    "Jirachi":bit0(0x02d8e9),
    "Deoxys":bit1(0x02d8e9),
    "Turtwig":bit2(0x02d8e9),
    "Grotle":bit3(0x02d8e9),
    "Torterra":bit4(0x02d8e9),
    "Chimchar":bit5(0x02d8e9),
    "Monferno":bit6(0x02d8e9),
    "Infernape":bit7(0x02d8e9),
    "Piplup":bit0(0x02d8ea),
    "Prinplup":bit1(0x02d8ea),
    "Empoleon":bit2(0x02d8ea),
    "Starly":bit3(0x02d8ea),
    "Staravia":bit4(0x02d8ea),
    "Staraptor":bit5(0x02d8ea),
    "Bidoof":bit6(0x02d8ea),
    "Bibarel":bit7(0x02d8ea),
    "Kricketot":bit0(0x02d8eb),
    "Kricketune":bit1(0x02d8eb),
    "Shinx":bit2(0x02d8eb),
    "Luxio":bit3(0x02d8eb),
    "Luxray":bit4(0x02d8eb),
    "Budew":bit5(0x02d8eb),
    "Roserade":bit6(0x02d8eb),
    "Cranidos":bit7(0x02d8eb),
    "Rampardos":bit0(0x02d8ec),
    "Shieldon":bit1(0x02d8ec),
    "Bastiodon":bit2(0x02d8ec),
    "Burmy":bit3(0x02d8ec),
    "Wormadam":bit4(0x02d8ec),
    "Mothim":bit5(0x02d8ec),
    "Combee":bit6(0x02d8ec),
    "Vespiquen":bit7(0x02d8ec),
    "Pachirisu":bit0(0x02d8ed),
    "Buizel":bit1(0x02d8ed),
    "Floatzel":bit2(0x02d8ed),
    "Cherubi":bit3(0x02d8ed),
    "Cherrim":bit4(0x02d8ed),
    "Shellos":bit5(0x02d8ed),
    "Gastrodon":bit6(0x02d8ed),
    "Ambipom":bit7(0x02d8ed),
    "Drifloon":bit0(0x02d8ee),
    "Drifblim":bit1(0x02d8ee),
    "Buneary":bit2(0x02d8ee),
    "Lopunny":bit3(0x02d8ee),
    "Mismagius":bit4(0x02d8ee),
    "Honchkrow":bit5(0x02d8ee),
    "Glameow":bit6(0x02d8ee),
    "Purugly":bit7(0x02d8ee),
    "Chingling":bit0(0x02d8ef),
    "Stunky":bit1(0x02d8ef),
    "Skuntank":bit2(0x02d8ef),
    "Bronzor":bit3(0x02d8ef),
    "Bronzong":bit4(0x02d8ef),
    "Bonsly":bit5(0x02d8ef),
    "Mime Jr.":bit6(0x02d8ef),
    "Happiny":bit7(0x02d8ef),
    "Chatot":bit0(0x02d8f0),
    "Spiritomb":bit1(0x02d8f0),
    "Gible":bit2(0x02d8f0),
    "Gabite":bit3(0x02d8f0),
    "Garchomp":bit4(0x02d8f0),
    "Munchlax":bit5(0x02d8f0),
    "Riolu":bit6(0x02d8f0),
    "Lucario":bit7(0x02d8f0),
    "Hippopotas":bit0(0x02d8f1),
    "Hippowdon":bit1(0x02d8f1),
    "Skorupi":bit2(0x02d8f1),
    "Drapion":bit3(0x02d8f1),
    "Croagunk":bit4(0x02d8f1),
    "Toxicroak":bit5(0x02d8f1),
    "Carnivine":bit6(0x02d8f1),
    "Finneon":bit7(0x02d8f1),
    "Lumineon":bit0(0x02d8f2),
    "Mantyke":bit1(0x02d8f2),
    "Snover":bit2(0x02d8f2),
    "Abomasnow":bit3(0x02d8f2),
    "Weavile":bit4(0x02d8f2),
    "Magnezone":bit5(0x02d8f2),
    "Lickilicky":bit6(0x02d8f2),
    "Rhyperior":bit7(0x02d8f2),
    "Tangrowth":bit0(0x02d8f3),
    "Electivire":bit1(0x02d8f3),
    "Magmortar":bit2(0x02d8f3),
    "Togekiss":bit3(0x02d8f3),
    "Yanmega":bit4(0x02d8f3),
    "Leafeon":bit5(0x02d8f3),
    "Glaceon":bit6(0x02d8f3),
    "Gliscor":bit7(0x02d8f3),
    "Mamoswine":bit0(0x02d8f4),
    "Porygon-Z":bit1(0x02d8f4),
    "Gallade":bit2(0x02d8f4),
    "Probopass":bit3(0x02d8f4),
    "Dusknoir":bit4(0x02d8f4),
    "Froslass":bit5(0x02d8f4),
    "Rotom":bit6(0x02d8f4),
    "Uxie":bit7(0x02d8f4),
    "Mesprit":bit0(0x02d8f5),
    "Azelf":bit1(0x02d8f5),
    "Dialga":bit2(0x02d8f5),
    "Palkia":bit3(0x02d8f5),
    "Heatran":bit4(0x02d8f5),
    "Regigigas":bit5(0x02d8f5),
    "Giratina":bit6(0x02d8f5),
    "Cresselia":bit7(0x02d8f5),
    "Phione":bit0(0x02d8f6),
    "Manaphy":bit1(0x02d8f6),
    "Darkrai":bit2(0x02d8f6),
    "Shaymin":bit3(0x02d8f6),
    "Arceus":bit4(0x02d8f6),
    "Victini":bit5(0x02d8f6),
    "Snivy":bit6(0x02d8f6),
    "Servine":bit7(0x02d8f6),
    "Serperior":bit0(0x02d8f7),
    "Tepig":bit1(0x02d8f7),
    "Pignite":bit2(0x02d8f7),
    "Emboar":bit3(0x02d8f7),
    "Oshawott":bit4(0x02d8f7),
    "Dewott":bit5(0x02d8f7),
    "Samurott":bit6(0x02d8f7),
    "Patrat":bit7(0x02d8f7),
    "Watchog":bit0(0x02d8f8),
    "Lillipup":bit1(0x02d8f8),
    "Herdier":bit2(0x02d8f8),
    "Stoutland":bit3(0x02d8f8),
    "Purrloin":bit4(0x02d8f8),
    "Liepard":bit5(0x02d8f8),
    "Pansage":bit6(0x02d8f8),
    "Simisage":bit7(0x02d8f8),
    "Pansear":bit0(0x02d8f9),
    "Simisear":bit1(0x02d8f9),
    "Panpour":bit2(0x02d8f9),
    "Simipour":bit3(0x02d8f9),
    "Munna":bit4(0x02d8f9),
    "Musharna":bit5(0x02d8f9),
    "Pidove":bit6(0x02d8f9),
    "Tranquill":bit7(0x02d8f9),
    "Unfezant":bit0(0x02d8fa),
    "Blitzle":bit1(0x02d8fa),
    "Zebstrika":bit2(0x02d8fa),
    "Roggenrola":bit3(0x02d8fa),
    "Boldore":bit4(0x02d8fa),
    "Gigalith":bit5(0x02d8fa),
    "Woobat":bit6(0x02d8fa),
    "Swoobat":bit7(0x02d8fa),
    "Drilbur":bit0(0x02d8fb),
    "Excadrill":bit1(0x02d8fb),
    "Audino":bit2(0x02d8fb),
    "Timburr":bit3(0x02d8fb),
    "Gurdurr":bit4(0x02d8fb),
    "Conkeldurr":bit5(0x02d8fb),
    "Tympole":bit6(0x02d8fb),
    "Palpitoad":bit7(0x02d8fb),
    "Seismitoad":bit0(0x02d8fc),
    "Throh":bit1(0x02d8fc),
    "Sawk":bit2(0x02d8fc),
    "Sewaddle":bit3(0x02d8fc),
    "Swadloon":bit4(0x02d8fc),
    "Leavanny":bit5(0x02d8fc),
    "Venipede":bit6(0x02d8fc),
    "Whirlipede":bit7(0x02d8fc),
    "Scolipede":bit0(0x02d8fd),
    "Cottonee":bit1(0x02d8fd),
    "Whimsicott":bit2(0x02d8fd),
    "Petilil":bit3(0x02d8fd),
    "Lilligant":bit4(0x02d8fd),
    "Basculin":bit5(0x02d8fd),
    "Sandile":bit6(0x02d8fd),
    "Krokorok":bit7(0x02d8fd),
    "Krookodile":bit0(0x02d8fe),
    "Darumaka":bit1(0x02d8fe),
    "Darmanitan":bit2(0x02d8fe),
    "Maractus":bit3(0x02d8fe),
    "Dwebble":bit4(0x02d8fe),
    "Crustle":bit5(0x02d8fe),
    "Scraggy":bit6(0x02d8fe),
    "Scrafty":bit7(0x02d8fe),
    "Sigilyph":bit0(0x02d8ff),
    "Yamask":bit1(0x02d8ff),
    "Cofagrigus":bit2(0x02d8ff),
    "Tirtouga":bit3(0x02d8ff),
    "Carracosta":bit4(0x02d8ff),
    "Archen":bit5(0x02d8ff),
    "Archeops":bit6(0x02d8ff),
    "Trubbish":bit7(0x02d8ff),
    "Garbodor":bit0(0x02d900),
    "Zorua":bit1(0x02d900),
    "Zoroark":bit2(0x02d900),
    "Minccino":bit3(0x02d900),
    "Cinccino":bit4(0x02d900),
    "Gothita":bit5(0x02d900),
    "Gothorita":bit6(0x02d900),
    "Gothitelle":bit7(0x02d900),
    "Solosis":bit0(0x02d901),
    "Duosion":bit1(0x02d901),
    "Reuniclus":bit2(0x02d901),
    "Ducklett":bit3(0x02d901),
    "Swanna":bit4(0x02d901),
    "Vanillite":bit5(0x02d901),
    "Vanillish":bit6(0x02d901),
    "Vanilluxe":bit7(0x02d901),
    "Deerling":bit0(0x02d902),
    "Sawsbuck":bit1(0x02d902),
    "Emolga":bit2(0x02d902),
    "Karrablast":bit3(0x02d902),
    "Escavalier":bit4(0x02d902),
    "Foongus":bit5(0x02d902),
    "Amoonguss":bit6(0x02d902),
    "Frillish":bit7(0x02d902),
    "Jellicent":bit0(0x02d903),
    "Alomomola":bit1(0x02d903),
    "Joltik":bit2(0x02d903),
    "Galvantula":bit3(0x02d903),
    "Ferroseed":bit4(0x02d903),
    "Ferrothorn":bit5(0x02d903),
    "Klink":bit6(0x02d903),
    "Klang":bit7(0x02d903),
    "Klinklang":bit0(0x02d904),
    "Tynamo":bit1(0x02d904),
    "Eelektrik":bit2(0x02d904),
    "Eelektross":bit3(0x02d904),
    "Elgyem":bit4(0x02d904),
    "Beheeyem":bit5(0x02d904),
    "Litwick":bit6(0x02d904),
    "Lampent":bit7(0x02d904),
    "Chandelure":bit0(0x02d905),
    "Axew":bit1(0x02d905),
    "Fraxure":bit2(0x02d905),
    "Haxorus":bit3(0x02d905),
    "Cubchoo":bit4(0x02d905),
    "Beartic":bit5(0x02d905),
    "Cryogonal":bit6(0x02d905),
    "Shelmet":bit7(0x02d905),
    "Accelgor":bit0(0x02d906),
    "Stunfisk":bit1(0x02d906),
    "Mienfoo":bit2(0x02d906),
    "Mienshao":bit3(0x02d906),
    "Druddigon":bit4(0x02d906),
    "Golett":bit5(0x02d906),
    "Golurk":bit6(0x02d906),
    "Pawniard":bit7(0x02d906),
    "Bisharp":bit0(0x02d907),
    "Bouffalant":bit1(0x02d907),
    "Rufflet":bit2(0x02d907),
    "Braviary":bit3(0x02d907),
    "Vullaby":bit4(0x02d907),
    "Mandibuzz":bit5(0x02d907),
    "Heatmor":bit6(0x02d907),
    "Durant":bit7(0x02d907),
    "Deino":bit0(0x02d908),
    "Zweilous":bit1(0x02d908),
    "Hydreigon":bit2(0x02d908),
    "Larvesta":bit3(0x02d908),
    "Volcarona":bit4(0x02d908),
    "Cobalion":bit5(0x02d908),
    "Terrakion":bit6(0x02d908),
    "Virizion":bit7(0x02d908),
    "Tornadus":bit0(0x02d909),
    "Thundurus":bit1(0x02d909),
    "Reshiram":bit2(0x02d909),
    "Zekrom":bit3(0x02d909),
    "Landorus":bit4(0x02d909),
    "Kyurem":bit5(0x02d909),
    "Keldeo":bit6(0x02d909),
    "Meloetta":bit7(0x02d909),
    "Genesect":bit0(0x02d90a),
    "Chespin":bit1(0x02d90a),
    "Quilladin":bit2(0x02d90a),
    "Chesnaught":bit3(0x02d90a),
    "Fennekin":bit4(0x02d90a),
    "Braixen":bit5(0x02d90a),
    "Delphox":bit6(0x02d90a),
    "Froakie":bit7(0x02d90a),
    "Frogadier":bit0(0x02d90b),
    "Greninja":bit1(0x02d90b),
    "Bunnelby":bit2(0x02d90b),
    "Diggersby":bit3(0x02d90b),
    "Fletchling":bit4(0x02d90b),
    "Fletchinder":bit5(0x02d90b),
    "Talonflame":bit6(0x02d90b),
    "Scatterbug":bit7(0x02d90b),
    "Spewpa":bit0(0x02d90c),
    "Vivillon":bit1(0x02d90c),
    "Litleo":bit2(0x02d90c),
    "Pyroar":bit3(0x02d90c),
    "Flabébé":bit4(0x02d90c),
    "Floette":bit5(0x02d90c),
    "Florges":bit6(0x02d90c),
    "Skiddo":bit7(0x02d90c),
    "Gogoat":bit0(0x02d90d),
    "Pancham":bit1(0x02d90d),
    "Pangoro":bit2(0x02d90d),
    "Furfrou":bit3(0x02d90d),
    "Espurr":bit4(0x02d90d),
    "Meowstic":bit5(0x02d90d),
    "Honedge":bit6(0x02d90d),
    "Doublade":bit7(0x02d90d),
    "Aegislash":bit0(0x02d90e),
    "Spritzee":bit1(0x02d90e),
    "Aromatisse":bit2(0x02d90e),
    "Swirlix":bit3(0x02d90e),
    "Slurpuff":bit4(0x02d90e),
    "Inkay":bit5(0x02d90e),
    "Malamar":bit6(0x02d90e),
    "Binacle":bit7(0x02d90e),
    "Barbaracle":bit0(0x02d90f),
    "Skrelp":bit1(0x02d90f),
    "Dragalge":bit2(0x02d90f),
    "Clauncher":bit3(0x02d90f),
    "Clawitzer":bit4(0x02d90f),
    "Helioptile":bit5(0x02d90f),
    "Heliolisk":bit6(0x02d90f),
    "Tyrunt":bit7(0x02d90f),
    "Tyrantrum":bit0(0x02d910),
    "Amaura":bit1(0x02d910),
    "Aurorus":bit2(0x02d910),
    "Sylveon":bit3(0x02d910),
    "Hawlucha":bit4(0x02d910),
    "Dedenne":bit5(0x02d910),
    "Carbink":bit6(0x02d910),
    "Goomy":bit7(0x02d910),
    "Sliggoo":bit0(0x02d911),
    "Goodra":bit1(0x02d911),
    "Klefki":bit2(0x02d911),
    "Phantump":bit3(0x02d911),
    "Trevenant":bit4(0x02d911),
    "Pumpkaboo":bit5(0x02d911),
    "Gourgeist":bit6(0x02d911),
    "Bergmite":bit7(0x02d911),
    "Avalugg":bit0(0x02d912),
    "Noibat":bit1(0x02d912),
    "Noivern":bit2(0x02d912),
    "Xerneas":bit3(0x02d912),
    "Yveltal":bit4(0x02d912),
    "Zygarde":bit5(0x02d912),
    "Diancie":bit6(0x02d912),
    "Hoopa":bit7(0x02d912),
    "Volcanion":bit0(0x02d913),
    "Rowlet":bit1(0x02d913),
    "Dartrix":bit2(0x02d913),
    "Decidueye":bit3(0x02d913),
    "Litten":bit4(0x02d913),
    "Torracat":bit5(0x02d913),
    "Incineroar":bit6(0x02d913),
    "Popplio":bit7(0x02d913),
    "Brionne":bit0(0x02d914),
    "Primarina":bit1(0x02d914),
    "Pikipek":bit2(0x02d914),
    "Trumbeak":bit3(0x02d914),
    "Toucannon":bit4(0x02d914),
    "Yungoos":bit5(0x02d914),
    "Gumshoos":bit6(0x02d914),
    "Grubbin":bit7(0x02d914),
    "Charjabug":bit0(0x02d915),
    "Vikavolt":bit1(0x02d915),
    "Crabrawler":bit2(0x02d915),
    "Crabominable":bit3(0x02d915),
    "Oricorio":bit4(0x02d915),
    "Cutiefly":bit5(0x02d915),
    "Ribombee":bit6(0x02d915),
    "Rockruff":bit7(0x02d915),
    "Lycanroc":bit0(0x02d916),
    "Wishiwashi":bit1(0x02d916),
    "Mareanie":bit2(0x02d916),
    "Toxapex":bit3(0x02d916),
    "Mudbray":bit4(0x02d916),
    "Mudsdale":bit5(0x02d916),
    "Dewpider":bit6(0x02d916),
    "Araquanid":bit7(0x02d916),
    "Fomantis":bit0(0x02d917),
    "Lurantis":bit1(0x02d917),
    "Morelull":bit2(0x02d917),
    "Shiinotic":bit3(0x02d917),
    "Salandit":bit4(0x02d917),
    "Salazzle":bit5(0x02d917),
    "Stufful":bit6(0x02d917),
    "Bewear":bit7(0x02d917),
    "Bounsweet":bit0(0x02d918),
    "Steenee":bit1(0x02d918),
    "Tsareena":bit2(0x02d918),
    "Comfey":bit3(0x02d918),
    "Oranguru":bit4(0x02d918),
    "Passimian":bit5(0x02d918),
    "Wimpod":bit6(0x02d918),
    "Golisopod":bit7(0x02d918),
    "Sandygast":bit0(0x02d919),
    "Palossand":bit1(0x02d919),
    "Pyukumuku":bit2(0x02d919),
    "Type: Null":bit3(0x02d919),
    "Silvally":bit4(0x02d919),
    "Minior":bit5(0x02d919),
    "Komala":bit6(0x02d919),
    "Turtonator":bit7(0x02d919),
    "Togedemaru":bit0(0x02d91a),
    "Mimikyu":bit1(0x02d91a),
    "Bruxish":bit2(0x02d91a),
    "Drampa":bit3(0x02d91a),
    "Dhelmise":bit4(0x02d91a),
    "Jangmo-o":bit5(0x02d91a),
    "Hakamo-o":bit6(0x02d91a),
    "Kommo-o":bit7(0x02d91a),
    "Tapu Koko":bit0(0x02d91b),
    "Tapu Lele":bit1(0x02d91b),
    "Tapu Bulu":bit2(0x02d91b),
    "Tapu Fini":bit3(0x02d91b),
    "Cosmog":bit4(0x02d91b),
    "Cosmoem":bit5(0x02d91b),
    "Solgaleo":bit6(0x02d91b),
    "Lunala":bit7(0x02d91b),
    "Nihilego":bit0(0x02d91c),
    "Buzzwole":bit1(0x02d91c),
    "Pheromosa":bit2(0x02d91c),
    "Xurkitree":bit3(0x02d91c),
    "Celesteela":bit4(0x02d91c),
    "Kartana":bit5(0x02d91c),
    "Guzzlord":bit6(0x02d91c),
    "Necrozma":bit7(0x02d91c),
    "Magearna":bit0(0x02d91d),
    "Marshadow":bit1(0x02d91d),
    "Poipole":bit2(0x02d91d),
    "Naganadel":bit3(0x02d91d),
    "Stakataka":bit4(0x02d91d),
    "Blacephalon":bit5(0x02d91d),
    "Zeraora":bit6(0x02d91d),
    "Meltan":bit7(0x02d91d),
    "Melmetal":bit0(0x02d91e)
}

function AreaLocation() => word(0x03ee0e)
function MapLocation() => word(0x03ee10)
function TrainerID() => word(0x02c592)
function SecretID() => word(0x02c594)
function BattleType() => byte(0x2be8a)
function LastBattledPokemon() => word(0x02bc3c)
function Music() => word(0x007300)
function SafariZonePokemonID() => word(0x008014)
function SafariZoneCount() => byte(0x008021)
function Location() => word(0x03edfc)
function CaughtPokemonAmount() => sum_of(range(0x2d8b9,0x2d91d,0x1), a => bitcount(a)) + bit0(0x2d91e)
function LastUsedPokeball() => word(0x2abcc)
function StarterChoice() => byte(0x43398)
function InGameTimerSeconds() => (word(0x02C596) * 3600) + (byte(0x02C598) * 60) + (byte(0x02C599)) // calibrated to real-world time, unaffected by speedup
function InGameTimerFrames() => (word(0x02C596) * 216000) + (byte(0x02C598) * 3600) + (byte(0x02C599) * 60) + (byte(0x02C59a))

function OptionsCheck() => byte(0x043532) != 01 && Location() != 0x5ae0 &&
bit4(0x043330) == 0 && bit0(0x043330) == 0 && bit5(0x043193) == 0 && 
bit6(0x043193) == 0 && bit3(0x04332F) == 0 && bit2(0x0432f8) == 0 && 
AreaLocation() != 0x0000 && prev(AreaLocation()) != 0x0000
&& ((byte(0x005ea9) == prior(byte(0x005ea9)) + 1) || (byte(0x005ea9) == 0x00 && prior(byte(0x005ea9)) == 0x3c))

badges = {
    "Leaf":bit0(0x02e510),
    "Vision":bit1(0x02e510),
    "Wings":bit2(0x02e510),
    "Fall":bit3(0x02e510),
    "Battery":bit4(0x02e510),
    "Ring":bit5(0x02e510),
    "Swamp":bit6(0x02e510),
    "Time":bit7(0x02e510),
    "Pokemon League":tbyte(0x02e754),
    "Postgame":0x0000
}

function obtain(pokemon, restriction, pokemon_amount=0) =>
OptionsCheck() && badges[restriction] == 0 && pokedex[pokemon] > prev(pokedex[pokemon])
&& (CaughtPokemonAmount() >= pokemon_amount || pokemon_amount == 0)
&& (restriction == "Time" || restriction == "Pokemon League" || restriction == "Postgame" || 
LastUsedPokeball() != 0x0001)

function catch(pokemon, restriction, species_id, pokemon_amount=0) =>
OptionsCheck() && badges[restriction] == 0 && BattleType() == 7 
&& LastBattledPokemon() == species_id && (CaughtPokemonAmount() >= pokemon_amount || pokemon_amount == 0)
&& (restriction == "Time" || restriction == "Pokemon League" || restriction == "Postgame" || 
LastUsedPokeball() != 0x0001)

function evolve(pokemon, restriction, species_id, pokemon_amount=0) => 
OptionsCheck() && badges[restriction] == 0 && Music() == 0x2e68 &&
any_of(range(0x02c2a4,0x02c498,step=0x64), a => word(a) == species_id && prev(word(a)) != species_id)
&& (CaughtPokemonAmount() >= pokemon_amount || pokemon_amount == 0)
&& (restriction == "Time" || restriction == "Pokemon League" || restriction == "Postgame" || 
LastUsedPokeball() != 0x0001)

function hatch(pokemon, restriction, species_id, pokemon_amount=0) => 
OptionsCheck() && badges[restriction] == 0 && Music() == 0x2e68 &&
any_of(range(0x02c2a4,0x02c498,step=0x64), a => word(a) == species_id && byte(a+0x34) == 1 && prior(byte(a+0x9)) == 0)
&& (CaughtPokemonAmount() >= pokemon_amount || pokemon_amount == 0)
&& (restriction == "Time" || restriction == "Pokemon League" || restriction == "Postgame" || 
LastUsedPokeball() != 0x0001)

function catch_safari(pokemon, restriction, species_id, pokemon_amount=0) =>
OptionsCheck() && badges[restriction] == 0 && SafariZonePokemonID() == species_id
&& SafariZoneCount() > prev(SafariZoneCount()) && (CaughtPokemonAmount() >= pokemon_amount || pokemon_amount == 0)

function unlockBadge(badge_name, gym_leader_name, location, pokemon_amount, extra_text=".", prev_text="all ") {
    achievement(
        title = badge_name + " Badge", 
        description = "Defeat " + gym_leader_name + " and obtain the " + badge_name + " Badge with " + prev_text + pokemon_amount + " Pokemon registered in the National Dex" + extra_text,
        points = 10,
        trigger = (
           CaughtPokemonAmount() >= pokemon_amount && AreaLocation() == location && badges[badge_name] > prev(badges[badge_name]) && OptionsCheck()
        )
    )
}

function startLeaderboard(badge_name, location, pokemon_amount) {
    return (
        CaughtPokemonAmount() >= pokemon_amount && AreaLocation() == location && badges[badge_name] > prev(badges[badge_name]) 
        && byte(0x043532) != 01 && Location() != 0x5ae0 &&
bit4(0x043330) == 0 && bit0(0x043330) == 0 && bit5(0x043193) == 0 && 
bit6(0x043193) == 0 && bit3(0x04332F) == 0 && bit2(0x0432f8) == 0 && 
AreaLocation() != 0x0000 && prev(AreaLocation()) != 0x0000
    )
}

function pokemonObtain(name, badge_name, point_amount, extra_text, pokemon_amount=1, area_location=0x0000) {
achievement(
    title = name, description = "Obtain " + name + extra_text, points = point_amount,
    trigger = (
    (
        always_false() || 
        obtain(name,badge_name,pokemon_amount)) &&
        (area_location == AreaLocation() || area_location == 0x0000)
    )
)
}

achievement(
    title = "INSTRUCTIONS", points = 0, id = 318451,
    description = "Battle difficulty must be Difficult or higher, turn off the level cap, no randomizer options, no New Game+, no mystery gifts, no trading, no changing your RTC.",
    trigger = byte(0x000000) == prev(byte(0x000000))
)

// Badge 1

function getBadge() => "Leaf"

achievement(
    title = "Starter I", id = 318452,
    description = "Choose either Larvitar, Beldum, or Gible to be your starter.", points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Larvitar",getBadge()) ||
        obtain("Beldum",getBadge()) ||
        obtain("Gible",getBadge()))
    ) 
    && MapLocation() == 0x0085
)
achievement(
    title = "Starter II", id = 318453,
    description = "Evolve your starter to become either Pupitar, Metang, or Gabite.", points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Pupitar",getBadge()) ||
        obtain("Metang",getBadge()) ||
        obtain("Gabite",getBadge()))
    )
)
achievement(
    title = "Starter III", id = 318454,
    description = "Evolve your starter to their final form as either Tyranitar, Metagross, or Garchomp.", points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Tyranitar",getBadge()) ||
        obtain("Metagross",getBadge()) ||
        obtain("Garchomp",getBadge()))
    )
)

// Route 1
pokemonObtain("Snorunt",getBadge(),1," on Route 1.",0)
pokemonObtain("Glalie",getBadge(),1," by evolving Snorunt.",0)
pokemonObtain("Vanillite",getBadge(),1," on Route 1.",0)
pokemonObtain("Vanillish",getBadge(),1," by evolving Vanillite.",0)
pokemonObtain("Vanilluxe",getBadge(),1," by evolving Vanillish.",0)
pokemonObtain("Delibird",getBadge(),1," on Route 1.",0)
pokemonObtain("Minior",getBadge(),1," on Route 1.",0)

// Icicle Cave
pokemonObtain("Zubat",getBadge(),1," in Icicle Cave.",0)
pokemonObtain("Golbat",getBadge(),1," by evolving Zubat.",0)
pokemonObtain("Crobat",getBadge(),1," by evolving Golbat.",0)
pokemonObtain("Makuhita",getBadge(),1," in Icicle Cave.",0)
pokemonObtain("Hariyama",getBadge(),1," by evolving Makuhita.",0)
pokemonObtain("Spheal",getBadge(),1," in Icicle Cave.",0)
pokemonObtain("Sealeo",getBadge(),1," by evolving Spheal.",0)
pokemonObtain("Walrein",getBadge(),1," by evolving Sealeo.",0)
pokemonObtain("Smoochum",getBadge(),1," in Icicle Cave.",0)
pokemonObtain("Jynx",getBadge(),1," by evolving Smoochum.",0)
pokemonObtain("Roggenrola",getBadge(),1," in Icicle Cave.",0)
pokemonObtain("Boldore",getBadge(),1," by evolving Roggenrola.",0)
pokemonObtain("Swinub",getBadge(),1," in Icicle Cave.",0)
pokemonObtain("Piloswine",getBadge(),1," by evolving Swinub.",0)
pokemonObtain("Bergmite",getBadge(),1," in Icicle Cave.",0)
pokemonObtain("Avalugg",getBadge(),1," by evolving Bergmite.",0)
pokemonObtain("Drilbur",getBadge(),1," in Icicle Cave.",0)
pokemonObtain("Excadrill",getBadge(),1," by evolving Drilbur.",0)
pokemonObtain("Mawile",getBadge(),1," in Icicle Cave.",0)
achievement(
    title = "Alolan Sandshrew", 
    description = "Obtain Alolan Sandshrew in Icicle Cave.", points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Sandshrew",getBadge()))
    )
)

// Route 2
pokemonObtain("Pikipek",getBadge(),1," on Route 2 (day).",0)
pokemonObtain("Trumbeak",getBadge(),1," by evolving Pikipek.",0)
pokemonObtain("Toucannon",getBadge(),1," by evolving Trumbeak.",0)
pokemonObtain("Hoothoot",getBadge(),1," on Route 2 (night).",0)
pokemonObtain("Noctowl",getBadge(),1," by evolving Hoothoot.",0)
pokemonObtain("Patrat",getBadge(),1," on Route 2 (day).",0)
pokemonObtain("Watchog",getBadge(),1," by evolving Patrat.",0)
pokemonObtain("Rattata",getBadge(),1," on Route 2 (night).",0)
pokemonObtain("Raticate",getBadge(),1," by evolving Rattata.",0)
pokemonObtain("Minccino",getBadge(),1," on Route 2.",0)
pokemonObtain("Electrike",getBadge(),1," on Route 2.",0)
pokemonObtain("Manectric",getBadge(),1," by evolving Electrike.",0)
pokemonObtain("Azurill",getBadge(),1," on Route 2.",0)
pokemonObtain("Marill",getBadge(),1," by evolving Azurill.",0)
pokemonObtain("Azumarill",getBadge(),1," by evolving Marill.",0)
pokemonObtain("Stufful",getBadge(),1," on Route 2.",0)
pokemonObtain("Bewear",getBadge(),1," by evolving Stufful.",0)
pokemonObtain("Scraggy",getBadge(),1," on Route 2.",0)
pokemonObtain("Scrafty",getBadge(),1," by evolving Scraggy.",0)
pokemonObtain("Riolu",getBadge(),1," on Route 2.",0)
pokemonObtain("Lucario",getBadge(),1," by evolving Riolu.",0)
pokemonObtain("Inkay",getBadge(),1," on Route 2.",0)
pokemonObtain("Malamar",getBadge(),1," by evolving Inkay.",0)
pokemonObtain("Poochyena",getBadge(),1," on Route 2 (swarm).",0)
pokemonObtain("Mightyena",getBadge(),1," by evolving Poochyena.",0)
pokemonObtain("Binacle",getBadge(),1," on Route 2 (static).",0)
pokemonObtain("Barbaracle",getBadge(),1," by evolving Binacle.",0)

// Route 3
pokemonObtain("Wingull",getBadge(),1," on Route 3.",0)
pokemonObtain("Pelipper",getBadge(),1," by evolving Wingull.",0)
pokemonObtain("Bidoof",getBadge(),1," on Route 3.",0)
pokemonObtain("Bibarel",getBadge(),1," by evolving Bidoof.",0)
pokemonObtain("Buizel",getBadge(),1," on Route 3.",0)
pokemonObtain("Floatzel",getBadge(),1," by evolving Buizel.",0)
pokemonObtain("Shellos",getBadge(),1," on Route 3.",0)
pokemonObtain("Gastrodon",getBadge(),1," by evolving Shellos.",0)
pokemonObtain("Dewpider",getBadge(),1," on Route 3 (day).",0)
pokemonObtain("Araquanid",getBadge(),1," by evolving Dewpider.",0)
pokemonObtain("Surskit",getBadge(),1," on Route 3 (night).",0)
pokemonObtain("Masquerain",getBadge(),1," by evolving Surskit.",0)
pokemonObtain("Cherubi",getBadge(),1," on Route 3 (day).",0)
pokemonObtain("Cherrim",getBadge(),1," by evolving Cherubi.",0)
pokemonObtain("Sandygast",getBadge(),1," on Route 3 (static encounter, Monday or Tuesday).",0)
pokemonObtain("Palossand",getBadge(),1," by evolving Sandygast.",0)
pokemonObtain("Poliwag",getBadge(),1," on Route 3.",0) // B325
pokemonObtain("Poliwhirl",getBadge(),1," by evolving Poliwag.",0)
pokemonObtain("Poliwrath",getBadge(),2," by evolving Poliwhirl (obtain Water Stone from Panpour).",0)
pokemonObtain("Slowpoke",getBadge(),1," on Route 3.",0) // B403
pokemonObtain("Slowbro",getBadge(),1," by evolving Slowpoke.",0)
pokemonObtain("Sentret",getBadge(),1," on Route 3 (swarm).",0)
pokemonObtain("Furret",getBadge(),1," by evolving Sentret.",0)

// Flower Paradise
pokemonObtain("Flabébé",getBadge(),1," in Flower Paradise.",0)
pokemonObtain("Floette",getBadge(),1," by evolving Flabébé.",0)
pokemonObtain("Cutiefly",getBadge(),1," in Flower Paradise.",0)
pokemonObtain("Ribombee",getBadge(),1," by evolving Cutiefly.",0)
pokemonObtain("Oricorio",getBadge(),1," in Flower Paradise.",0)
pokemonObtain("Pansage",getBadge(),1," in Flower Paradise.",0)
pokemonObtain("Simisage",getBadge(),2," by evolving Pansage (obtain Leaf Stone from Pansage).",0)
pokemonObtain("Pansear",getBadge(),1," in Flower Paradise.",0)
pokemonObtain("Simisear",getBadge(),2," by evolving Pansear (obtain Fire Stone from Pansear).",0)
pokemonObtain("Panpour",getBadge(),1," in Flower Paradise.",0)
pokemonObtain("Simipour",getBadge(),2," by evolving Panpour (obtain Water Stone from Panpour).",0)
pokemonObtain("Combee",getBadge(),1," in Flower Paradise.",0)
pokemonObtain("Vespiquen",getBadge(),1," by evolving Combee (female).",0)
pokemonObtain("Comfey",getBadge(),1," in Flower Paradise.",0)

// Other
pokemonObtain("Ducklett",getBadge(),1," by trading an Alolan Sandshrew with the Old Man in Dresco Town.",0,0x01f0)
pokemonObtain("Swanna",getBadge(),1," by evolving Ducklett.",0)
pokemonObtain("Litleo",getBadge(),1," as a gift for beating the Challenge Road (on Route 2).",0)
pokemonObtain("Pyroar",getBadge(),1," by evolving Litleo.",0)
achievement(
    title = "Bellin Town Gift I", 
    description = "Obtain either Skorupi, Glameow, or Stunky from a gentleman in Bellin Town.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Skorupi",getBadge()) || // no modulo :(
        obtain("Glameow",getBadge()) ||
        obtain("Stunky",getBadge()))
    ) && AreaLocation() == 0x01bb
)
achievement(
    title = "Bellin Town Gift II", 
    description = "Evolve your gift to their final form as either Drapion, Purugly, or Skuntank.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Drapion",getBadge()) ||
        obtain("Purugly",getBadge()) ||
        obtain("Skuntank",getBadge()))
    )
)

function getTotalPokemonCount() => 100
unlockBadge(getBadge(), "Mirskle", 0x019f, getTotalPokemonCount())
leaderboard(
    getBadge() + " Badge Speedrun",
    "Fastest in-game time to obtain the " + getBadge() + " Badge with all " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x019f, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Badge 2

function getBadge() => "Vision"

pokemonObtain("Froslass",getBadge(),2," by evolving Snorunt (obtain Dawn Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Gigalith",getBadge(),2," by evolving Boldore (obtain Link Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Mamoswine",getBadge(),2," by evolving Piloswine (while knowing Ancient Power).",getTotalPokemonCount())
pokemonObtain("Cinccino",getBadge(),2," by evolving Minccino (obtain Shiny Stone via Miner NPC or Lillipup Pickup).",getTotalPokemonCount())
pokemonObtain("Florges",getBadge(),2," by evolving Floette (obtain Shiny Stone via Miner NPC or Lillipup Pickup).",getTotalPokemonCount())
pokemonObtain("Politoed",getBadge(),2," by evolving Poliwhirl (obtain King's Rock from Lillipup Pickup).",getTotalPokemonCount())
pokemonObtain("Slowking",getBadge(),2," by evolving Slowpoke (obtain King's Rock from Lillipup Pickup).",getTotalPokemonCount())
achievement(
    title = "Alolan Sandslash", 
    description = "Obtain Alolan Sandslash by evolving Alolan Sandshrew (Ice Stone).", points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Sandslash",getBadge(),getTotalPokemonCount()))
    )
)

// Grim Woods
pokemonObtain("Caterpie",getBadge(),1," in Grim Woods (day).",getTotalPokemonCount())
pokemonObtain("Metapod",getBadge(),1," by evolving Caterpie.",getTotalPokemonCount())
pokemonObtain("Butterfree",getBadge(),1," by evolving Butterfree.",getTotalPokemonCount())
pokemonObtain("Weedle",getBadge(),1," in Grim Woods (night).",getTotalPokemonCount())
pokemonObtain("Kakuna",getBadge(),1," by evolving Weedle.",getTotalPokemonCount())
pokemonObtain("Beedrill",getBadge(),1," by evolving Kakuna.",getTotalPokemonCount())
pokemonObtain("Seedot",getBadge(),1," in Grim Woods.",getTotalPokemonCount())
pokemonObtain("Nuzleaf",getBadge(),1," by evolving Seedot.",getTotalPokemonCount())
pokemonObtain("Shiftry",getBadge(),2," by evolving Nuzleaf (Leaf Stone).",getTotalPokemonCount())
pokemonObtain("Pumpkaboo",getBadge(),1," in Grim Woods.",getTotalPokemonCount())
pokemonObtain("Gourgeist",getBadge(),2," by evolving Pumpkaboo (obtain Link Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Gastly",getBadge(),1," in Grim Woods.",getTotalPokemonCount())
pokemonObtain("Haunter",getBadge(),1," by evolving Gastly.",getTotalPokemonCount())
pokemonObtain("Gengar",getBadge(),2," by evolving Haunter (obtain Link Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Shuppet",getBadge(),1," in Grim Woods.",getTotalPokemonCount())
pokemonObtain("Banette",getBadge(),1," by evolving Shuppet.",getTotalPokemonCount())
pokemonObtain("Duskull",getBadge(),1," in Grim Woods.",getTotalPokemonCount())
pokemonObtain("Dusclops",getBadge(),1," by evolving Duskull.",getTotalPokemonCount())
pokemonObtain("Phantump",getBadge(),1," in Grim Woods.",getTotalPokemonCount())
pokemonObtain("Trevenant",getBadge(),2," by evolving Phantump (obtain Link Stone via Miner NPC).",getTotalPokemonCount())

// Route 4
pokemonObtain("Starly",getBadge(),1," on Route 4 (day).",getTotalPokemonCount())
pokemonObtain("Staravia",getBadge(),1," by evolving Starly.",getTotalPokemonCount())
pokemonObtain("Staraptor",getBadge(),1," by evolving Staraptor.",getTotalPokemonCount())
pokemonObtain("Lillipup",getBadge(),1," on Route 4.",getTotalPokemonCount())
pokemonObtain("Herdier",getBadge(),1," by evolving Lillipup.",getTotalPokemonCount())
pokemonObtain("Stoutland",getBadge(),1," by evolving Herdier.",getTotalPokemonCount())
pokemonObtain("Budew",getBadge(),1," on Route 4.",getTotalPokemonCount())
pokemonObtain("Roselia",getBadge(),1," by evolving Budew (high friendship, day).",getTotalPokemonCount())
pokemonObtain("Roserade",getBadge(),2," by evolving Roselia (obtain Shiny Stone via Miner NPC or Lillipup Pickup).",getTotalPokemonCount())
pokemonObtain("Ekans",getBadge(),1," on Route 4.",getTotalPokemonCount())
pokemonObtain("Arbok",getBadge(),1," by evolving Ekans.",getTotalPokemonCount())
pokemonObtain("Numel",getBadge(),1," on Route 4 or Cinder Volcano.",getTotalPokemonCount())
pokemonObtain("Camerupt",getBadge(),1," by evolving Numel.",getTotalPokemonCount())
pokemonObtain("Mankey",getBadge(),1," on Route 4.",getTotalPokemonCount())
pokemonObtain("Primeape",getBadge(),1," by evolving Mankey.",getTotalPokemonCount())
pokemonObtain("Ralts",getBadge(),1," on Route 4.",getTotalPokemonCount())
pokemonObtain("Kirlia",getBadge(),1," by evolving Ralts.",getTotalPokemonCount())
pokemonObtain("Gardevoir",getBadge(),1," by evolving Kirlia.",getTotalPokemonCount())
pokemonObtain("Gallade",getBadge(),2," by evolving Kirlia (male, obtain Dawn Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Burmy",getBadge(),1," on Route 4 (swarm).",getTotalPokemonCount())
pokemonObtain("Wormadam",getBadge(),1," by evolving Burmy (female).",getTotalPokemonCount())
pokemonObtain("Mothim",getBadge(),1," by evolving Burmy (male).",getTotalPokemonCount())

// Cinder Volcano
pokemonObtain("Woobat",getBadge(),1," in Cinder Volcano or in the KBT Expressway (from Crater Town).",getTotalPokemonCount())
pokemonObtain("Swoobat",getBadge(),1," by evolving Woobat.",getTotalPokemonCount())
pokemonObtain("Slugma",getBadge(),1," in Cinder Volcano.",getTotalPokemonCount())
pokemonObtain("Magcargo",getBadge(),1," by evolving Slugma.",getTotalPokemonCount())
pokemonObtain("Salandit",getBadge(),1," in Cinder Volcano.",getTotalPokemonCount())
pokemonObtain("Salazzle",getBadge(),1," by evolving Salandit (female).",getTotalPokemonCount())
pokemonObtain("Geodude",getBadge(),1," in Cinder Volcano or in the KBT Expressway (from Crater Town).",getTotalPokemonCount())
pokemonObtain("Graveler",getBadge(),1," by evolving Geodude.",getTotalPokemonCount())
pokemonObtain("Golem",getBadge(),2," by evolving Graveler (obtain Link Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Torkoal",getBadge(),1," in Cinder Volcano.",getTotalPokemonCount())
pokemonObtain("Magby",getBadge(),1," in Cinder Volcano.",getTotalPokemonCount())
pokemonObtain("Magmar",getBadge(),1," by evolving Magby.",getTotalPokemonCount())
pokemonObtain("Magmortar",getBadge(),2," by evolving Magmar (obtain Magmarizer from Magby).",getTotalPokemonCount())
pokemonObtain("Vulpix",getBadge(),1," in Cinder Volcano (swarm).",getTotalPokemonCount())
pokemonObtain("Ninetales",getBadge(),1," by evolving Vulpix (Fire Stone).",getTotalPokemonCount())

// Route 5
pokemonObtain("Taillow",getBadge(),1," on Route 5 (day).",getTotalPokemonCount())
pokemonObtain("Swellow",getBadge(),1," by evolving Taillow.",getTotalPokemonCount())
pokemonObtain("Murkrow",getBadge(),1," on Route 5 (night).",getTotalPokemonCount())
pokemonObtain("Honchkrow",getBadge(),2," by evolving Murkrow (obtain Dusk Stone via Miner NPC or Lillipup Pickup).",getTotalPokemonCount())
pokemonObtain("Lickitung",getBadge(),1," on Route 5.",getTotalPokemonCount())
pokemonObtain("Lickilicky",getBadge(),1," by evolving Lickitung (while knowing Rollout).",getTotalPokemonCount())
pokemonObtain("Nidoran♂",getBadge(),1," on Route 5.",getTotalPokemonCount())
pokemonObtain("Nidorino",getBadge(),1," by evolving Nidoran♂.",getTotalPokemonCount())
pokemonObtain("Nidoking",getBadge(),2," by evolving Nidorino (obtain Moon Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Nidoran♀",getBadge(),1," on Route 5.",getTotalPokemonCount())
pokemonObtain("Nidorina",getBadge(),1," by evolving Nidoran♀.",getTotalPokemonCount())
pokemonObtain("Nidoqueen",getBadge(),2," by evolving Nidorina (obtain Moon Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Growlithe",getBadge(),1," on Route 5 (day).",getTotalPokemonCount())
pokemonObtain("Arcanine",getBadge(),2," by evolving Growlithe (Fire Stone).",getTotalPokemonCount())
pokemonObtain("Houndour",getBadge(),1," on Route 5 (night).",getTotalPokemonCount())
pokemonObtain("Houndoom",getBadge(),1," by evolving Houndour.",getTotalPokemonCount())
pokemonObtain("Yanma",getBadge(),1," on Route 5 (day).",getTotalPokemonCount())
pokemonObtain("Yanmega",getBadge(),1," by evolving Yanma (while knowing Ancient Power).",getTotalPokemonCount())
pokemonObtain("Venonat",getBadge(),1," on Route 5.",getTotalPokemonCount())
pokemonObtain("Venomoth",getBadge(),1," by evolving Venonat.",getTotalPokemonCount())
pokemonObtain("Purrloin",getBadge(),1," on Route 5.",getTotalPokemonCount())
pokemonObtain("Liepard",getBadge(),1," by evolving Purrloin.",getTotalPokemonCount())
pokemonObtain("Elgyem",getBadge(),1," on Route 5 (swarm).",getTotalPokemonCount())
pokemonObtain("Beheeyem",getBadge(),1," by evolving Elgyem.",getTotalPokemonCount())
pokemonObtain("Ditto",getBadge(),1," on Route 5.",getTotalPokemonCount())

// KBT Expressway
pokemonObtain("Aron",getBadge(),1," in the KBT Expressway (fron Crater Town).",getTotalPokemonCount())
pokemonObtain("Lairon",getBadge(),1," by evolving Aron.",getTotalPokemonCount())
pokemonObtain("Aggron",getBadge(),1," by evolving Lairon.",getTotalPokemonCount())
pokemonObtain("Nosepass",getBadge(),1," in the KBT Expressway (from Crater Town).",getTotalPokemonCount())
pokemonObtain("Probopass",getBadge(),2," by evolving Nosepass (obtain Thunder Stone via Miner NPC).",getTotalPokemonCount())
pokemonObtain("Noibat",getBadge(),1," in the KBT Expressway (from Crater Town).",getTotalPokemonCount())
pokemonObtain("Noivern",getBadge(),1," by evolving Noibat.",getTotalPokemonCount())

// Other
pokemonObtain("Cleffa",getBadge(),1," by breeding Clefairy.",getTotalPokemonCount())
pokemonObtain("Clefairy",getBadge(),1," from the Crater Town bookshelf.",getTotalPokemonCount())
pokemonObtain("Clefable",getBadge(),2," by evolving Clefairy (obtain Moon Stone via Miner NPC).",getTotalPokemonCount())
achievement(
    title = "Unova Starters I", 
    description = "Obtain either Snivy, Tepig, or Oshawott from a girl on Route 5.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Snivy",getBadge(),getTotalPokemonCount()) ||
        obtain("Tepig",getBadge(),getTotalPokemonCount()) ||
        obtain("Oshawott",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Unova Starters II", 
    description = "Evolve your Unova starter to become either Servine, Pignite, or Dewott.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Servine",getBadge(),getTotalPokemonCount()) ||
        obtain("Pignite",getBadge(),getTotalPokemonCount()) ||
        obtain("Dewott",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Unova Starters III", 
    description = "Evolve your Unova starter to their final form as either Serperior, Emboar, or Samurott.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Serperior",getBadge(),getTotalPokemonCount()) ||
        obtain("Emboar",getBadge(),getTotalPokemonCount()) ||
        obtain("Samurott",getBadge(),getTotalPokemonCount()))
    )
)
pokemonObtain("Zygarde",getBadge(),2," by assembling 10% of the Zygarde Cells.",getTotalPokemonCount())

function getTotalPokemonCount() => 204
unlockBadge(getBadge(), "Véga", 0x001c, getTotalPokemonCount())
leaderboard(
    getBadge() + " Badge Speedrun",
    "Fastest in-game time to obtain the " + getBadge() + " Badge with all " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x001c, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Badge 3

function getBadge() => "Wings"

// Valley Cave
pokemonObtain("Phanpy",getBadge(),1," in Valley Cave.",getTotalPokemonCount())
pokemonObtain("Donphan",getBadge(),1," by evolving Phanpy.",getTotalPokemonCount())
pokemonObtain("Gligar",getBadge(),1," in Valley Cave.",getTotalPokemonCount())
pokemonObtain("Dunsparce",getBadge(),1," in Valley Cave.",getTotalPokemonCount())

// Route 6
pokemonObtain("Bunnelby",getBadge(),1," on Route 6.",getTotalPokemonCount())
pokemonObtain("Diggersby",getBadge(),1," by evolving Bunnelby.",getTotalPokemonCount())
pokemonObtain("Ledyba",getBadge(),1," on Route 6 (day) or at the Route 6 Raid Den.",getTotalPokemonCount())
pokemonObtain("Ledian",getBadge(),1," on Route 6 (day) or by evolving Ledyba or at the Route 6 Raid Den.",getTotalPokemonCount())
pokemonObtain("Spinarak",getBadge(),1," on Route 6 (night) or at the Route 6 Raid Den.",getTotalPokemonCount())
pokemonObtain("Ariados",getBadge(),1," on Route 6 (night) or by evolving Spinarak or at the Route 6 Raid Den.",getTotalPokemonCount())
pokemonObtain("Shinx",getBadge(),1," on Route 6 or 7.",getTotalPokemonCount())
pokemonObtain("Luxio",getBadge(),1," on Route 6 or 7 or by evolving Shinx or at the Route 6 Raid Den.",getTotalPokemonCount())
pokemonObtain("Luxray",getBadge(),1," by evolving Luxio.",getTotalPokemonCount())
pokemonObtain("Deerling",getBadge(),1," on Route 6 or 8 or at the Route 6 Raid Den.",getTotalPokemonCount())
pokemonObtain("Sawsbuck",getBadge(),1," by evolving Deerling.",getTotalPokemonCount())
pokemonObtain("Sunkern",getBadge(),1," on Route 6 (day) or at the Route 6 Raid Den.",getTotalPokemonCount())
pokemonObtain("Sunflora",getBadge(),2," by evolving Sunkern (Sun Stone from Miner NPC or obtain from the Sun Trio).",getTotalPokemonCount())
pokemonObtain("Kricketot",getBadge(),1," on Route 6 (night).",getTotalPokemonCount())
pokemonObtain("Kricketune",getBadge(),1," by evolving Kricketot or at the Route 6 Raid Den.",getTotalPokemonCount())
pokemonObtain("Smeargle",getBadge(),1," on Route 6 (swarm) or at the Route 6 Raid Den.",getTotalPokemonCount())

// Route 7
pokemonObtain("Yungoos",getBadge(),1," on Route 7 (day) or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Gumshoos",getBadge(),1," on Route 7 (day) or by evolving Yungoos or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Doduo",getBadge(),1," on Route 7 (day) or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Dodrio",getBadge(),1," by evolving Doduo.",getTotalPokemonCount())
pokemonObtain("Buneary",getBadge(),1," on Route 7 or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Lopunny",getBadge(),1," by evolving Buneary (high friendship).",getTotalPokemonCount())
pokemonObtain("Abra",getBadge(),1," on Route 7 or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Kadabra",getBadge(),1," by evolving Abra or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Alakazam",getBadge(),2," by evolving Kadabra (Link Stone).",getTotalPokemonCount())
pokemonObtain("Mareep",getBadge(),1," on Route 7.",getTotalPokemonCount())
pokemonObtain("Meowstic",getBadge(),1," by evolving Espurr or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Espurr",getBadge(),1," on Route 7 (day) or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Drowzee",getBadge(),1," on Route 7 (night) or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Hypno",getBadge(),1," by evolving Drowzee.",getTotalPokemonCount())
pokemonObtain("Mr. Mime",getBadge(),1," on Route 7 (swarm) or at the Route 7 Raid Den.",getTotalPokemonCount())
achievement(
    title = "Alolan Rattata", description = "Obtain Alolan Rattata on Route 7 (night) or at the Route 7 Raid Den.", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Alolan Rattata",getBadge(),0x3fc,getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Raticate", description = "Obtain Alolan Raticate on Route 7 (night) or by evolving Alolan Rattata or at the Route 7 Raid Den.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Alolan Raticate",getBadge(),0x3fd,getTotalPokemonCount()) ||
        catch("Alolan Raticate",getBadge(),0x3fd,getTotalPokemonCount()))
    )
)

// Route 8
pokemonObtain("Flaaffy",getBadge(),1," on Route 8 or by evolving Mareep or at the Route 7 Raid Den.",getTotalPokemonCount())
pokemonObtain("Ampharos",getBadge(),1," by evolving Flaaffy.",getTotalPokemonCount())
pokemonObtain("Snover",getBadge(),1," on Route 8 or Frozen Forest.",getTotalPokemonCount())
pokemonObtain("Abomasnow",getBadge(),1," by evolving Snover.",getTotalPokemonCount())
pokemonObtain("Cubchoo",getBadge(),1," on Route 8 or Frozen Forest.",getTotalPokemonCount())
pokemonObtain("Beartic",getBadge(),1," by evolving Cubchoo.",getTotalPokemonCount())

// Frost Mountain
pokemonObtain("Bronzor",getBadge(),1," on Frost Mountain.",getTotalPokemonCount())
pokemonObtain("Bronzong",getBadge(),1," by evolving Bronzor.",getTotalPokemonCount())
pokemonObtain("Onix",getBadge(),1," on Frost Mountain.",getTotalPokemonCount())
pokemonObtain("Steelix",getBadge(),2," by evolving Onix (obtain Metal Coat from Mawile).",getTotalPokemonCount())
pokemonObtain("Sneasel",getBadge(),1," on Frost Mountain, on Route 8 (night), or Frozen Forest (night).",getTotalPokemonCount())
pokemonObtain("Cryogonal",getBadge(),1," on Frost Mountain.",getTotalPokemonCount())
pokemonObtain("Stantler",getBadge(),1," on Frost Mountain (swarm).",getTotalPokemonCount())

// Other
pokemonObtain("Magikarp",getBadge(),1," by fishing anywhere with the Old Rod.",getTotalPokemonCount())
pokemonObtain("Gyarados",getBadge(),1," by evolving Magikarp.",getTotalPokemonCount())
pokemonObtain("Crabrawler",getBadge(),1," by breeding Crabominable.",getTotalPokemonCount())
pokemonObtain("Crabominable",getBadge(),1," during the Nine Tails of Snow mission, or at the Frozen Forest (Thursday).",getTotalPokemonCount())
pokemonObtain("Voltorb",getBadge(),1," by breeding Electrode.",getTotalPokemonCount())
pokemonObtain("Electrode",getBadge(),1," by trading an Onix with the girl in Blizzard City.",getTotalPokemonCount())
achievement(
    title = "Alolan Vulpix", description = "Obtain Alolan Vulpix as an Egg received from the Nine Tails of Snow mission.", points = 1,
    trigger = (
    (
        always_false() || 
        hatch("Alolan Vulpix",getBadge(),0x401,getTotalPokemonCount())) && bit2(0x4346c) == 1
    )
)
achievement(
    title = "Alolan Ninetales", description = "Obtain Alolan Ninetales by evolving Alolan Vulpix (Ice Stone).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Alolan Ninetales",getBadge(),0x402,getTotalPokemonCount())) && bit2(0x4346c) == 1
    )
)

function getTotalPokemonCount() => 258
unlockBadge(getBadge(), "Alice", 0x00b5, getTotalPokemonCount(), " (+4 variations).")
leaderboard(
    getBadge() + " Badge Speedrun",
    "Fastest in-game time to obtain the " + getBadge() + " Badge with all " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x00b5, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Badge 4

function getBadge() => "Fall"

pokemonObtain("Krabby",getBadge(),1," on Route 2 (rock smash).",getTotalPokemonCount())
pokemonObtain("Kingler",getBadge(),1," by evolving Krabby.",getTotalPokemonCount())
pokemonObtain("Shuckle",getBadge(),1," from Icicle Cave or Cinder Volcano Rock Smash.",getTotalPokemonCount())
pokemonObtain("Gliscor",getBadge(),2," by evolving Gligar (while holding a Razor Fang at night).",getTotalPokemonCount())

// Route 9
pokemonObtain("Spearow",getBadge(),1," on Route 9 or Autl Woods.",getTotalPokemonCount())
pokemonObtain("Fearow",getBadge(),1," by evolving Spearow or at the Route 9 Raid Den.",getTotalPokemonCount())
pokemonObtain("Grubbin",getBadge(),1," on Route 9 or Autl Woods.",getTotalPokemonCount())
pokemonObtain("Charjabug",getBadge(),1," by evolving Grubbin or at the Route 9 Raid Den.",getTotalPokemonCount())
pokemonObtain("Vikavolt",getBadge(),2," by evolving Charjabug (Thunder Stone).",getTotalPokemonCount())
pokemonObtain("Shroomish",getBadge(),1," on Route 9 or Autl Woods.",getTotalPokemonCount())
pokemonObtain("Breloom",getBadge(),1," by evolving Shroomish or at the Route 9 Raid Den.",getTotalPokemonCount())
pokemonObtain("Audino",getBadge(),1," on Route 9 or Autl Woods or at the Route 9 Raid Den.",getTotalPokemonCount())
pokemonObtain("Karrablast",getBadge(),1," on Route 9 (swarm) or at the Route 9 Raid Den.",getTotalPokemonCount())
pokemonObtain("Escavalier",getBadge(),2," by evolving Karrablast (Link Stone).",getTotalPokemonCount())
achievement(
    title = "Skorupi", description = "Obtain Skorupi on Route 9 or Autl Woods or at the Route 9 Raid Den.", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Skorupi",getBadge(),0x1f8,getTotalPokemonCount())) || (AreaLocation() == 0x00b5 && pokedex["Skorupi"] == 1 && badges["Wings"] == 1 && OptionsCheck())
    )
)
achievement(
    title = "Drapion", description = "Obtain Drapion by evolving Skorupi.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Drapion",getBadge(),0x1f9,getTotalPokemonCount())) || (AreaLocation() == 0x00b5 && pokedex["Drapion"] == 1 && badges["Wings"] == 1 && OptionsCheck())
    )
)

// Route 10
pokemonObtain("Lotad",getBadge(),1," on Route 10.",getTotalPokemonCount())
pokemonObtain("Lombre",getBadge(),1," on Route 10 or by evolving Lotad or at the Route 10 Raid Den or at the Fallshore City Gym.",getTotalPokemonCount())
pokemonObtain("Ludicolo",getBadge(),2," by evolving Lombre (Water Stone).",getTotalPokemonCount())
pokemonObtain("Tympole",getBadge(),1," on Route 10.",getTotalPokemonCount())
pokemonObtain("Palpitoad",getBadge(),1," on Route 10 or by evolving Tympole or at the Route 10 Raid Den.",getTotalPokemonCount())
pokemonObtain("Seismitoad",getBadge(),1," by evolving Palpitoad.",getTotalPokemonCount())
pokemonObtain("Zigzagoon",getBadge(),1," by breeding Linoone.",getTotalPokemonCount())
pokemonObtain("Linoone",getBadge(),1," on Route 10 or at the Route 10 Raid Den.",getTotalPokemonCount())
pokemonObtain("Goomy",getBadge(),1," on Route 10 or at the Route 10 Raid Den.",getTotalPokemonCount())
achievement(
    title = "Sliggoo", description = "Obtain Sliggoo by evolving Goomy.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Sliggoo",getBadge(),0x32d,getTotalPokemonCount()))
    )
)
achievement(
    title = "Goodra", description = "Obtain Goodra by evolving Sliggoo.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Goodra",getBadge(),0x32e,getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Sliggoo", description = "Obtain Hisuian Sliggoo by evolving Goomy (Hisui Rock).", points = 2,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Sliggoo",getBadge(),0x4df,getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Goodra", description = "Obtain Hisuian Goodra by evolving Hisuian Sliggoo.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Goodra",getBadge(),0x4e0,getTotalPokemonCount()))
    )
)
pokemonObtain("Shelmet",getBadge(),1," on Route 10 (swarm) or at the Route 10 Raid Den.",getTotalPokemonCount())
pokemonObtain("Accelgor",getBadge(),2," by evolving Shelmet (Link Stone).",getTotalPokemonCount())

// Route 11
pokemonObtain("Exeggcute",getBadge(),1," on Route 11.",getTotalPokemonCount())
pokemonObtain("Exeggutor",getBadge(),2," by evolving Exeggcute (Leaf Stone).",getTotalPokemonCount())
pokemonObtain("Swablu",getBadge(),1," on Route 11 (day).",getTotalPokemonCount())
pokemonObtain("Altaria",getBadge(),1," by evolving Swablu.",getTotalPokemonCount())
pokemonObtain("Togedemaru",getBadge(),1," on Route 11.",getTotalPokemonCount())
pokemonObtain("Spoink",getBadge(),1," on Route 11.",getTotalPokemonCount())
pokemonObtain("Grumpig",getBadge(),1," by evolving Spoink.",getTotalPokemonCount())
pokemonObtain("Meditite",getBadge(),1," on Route 11.",getTotalPokemonCount())
pokemonObtain("Medicham",getBadge(),1," by evolving Meditite.",getTotalPokemonCount())
pokemonObtain("Gulpin",getBadge(),1," on Route 11.",getTotalPokemonCount())
pokemonObtain("Swalot",getBadge(),1," by evolving Gulpin.",getTotalPokemonCount())
achievement(
    title = "Glameow", description = "Obtain Glameow on Route 11 (swarm).", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Glameow",getBadge(),0x1e4,getTotalPokemonCount())) || (AreaLocation() == 0x00b5 && pokedex["Glameow"] == 1 && badges["Wings"] == 1 && OptionsCheck())
    )
)
achievement(
    title = "Purugly", description = "Obtain Purugly by evolving Glameow.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Purugly",getBadge(),0x1e5,getTotalPokemonCount())) || (AreaLocation() == 0x00b5 && pokedex["Purugly"] == 1 && badges["Wings"] == 1 && OptionsCheck())
    )
)

// Fishing
pokemonObtain("Seel",getBadge(),1," by fishing with a Good Rod (Icicle Cave, Frost Mtn).",getTotalPokemonCount())
pokemonObtain("Dewgong",getBadge(),1," by evolving Seel.",getTotalPokemonCount())
pokemonObtain("Shellder",getBadge(),1," by fishing with a Good Rod (on Routes 2, 3, Dresco Town, Icicle Cave, Frost Mountain).",getTotalPokemonCount())
pokemonObtain("Cloyster",getBadge(),2," by evolving Shellder (Water Stone).",getTotalPokemonCount())
pokemonObtain("Staryu",getBadge(),1," by fishing with a Good Rod (on Routes 2, 3, 4, 5, Dresco Town).",getTotalPokemonCount())
pokemonObtain("Starmie",getBadge(),2," by evolving Staryu (Water Stone).",getTotalPokemonCount())
pokemonObtain("Corphish",getBadge(),1," by fishing with a Good Rod (on Routes 4, 5).",getTotalPokemonCount())
pokemonObtain("Crawdaunt",getBadge(),1," by evolving Corphish.",getTotalPokemonCount())
pokemonObtain("Goldeen",getBadge(),1," by fishing with a Good Rod (on Routes 6, 7, 9, Tehl Town, Auburn Waterway, Autl Woods).",getTotalPokemonCount())
pokemonObtain("Seaking",getBadge(),1," by evolving Goldeen.",getTotalPokemonCount())
pokemonObtain("Remoraid",getBadge(),1," by fishing with a Good Rod (on Routes 6, 7, 9, Tehl Town, Auburn Waterway).",getTotalPokemonCount())
pokemonObtain("Octillery",getBadge(),1," by evolving Remoraid.",getTotalPokemonCount())
pokemonObtain("Wishiwashi",getBadge(),1," by fishing with a Good Rod (on Routes 9, 10, Tehl Town, Auburn Waterway, Autl Woods).",getTotalPokemonCount())
pokemonObtain("Carvanha",getBadge(),1," by fishing with a Good Rod (Fallshore City).",getTotalPokemonCount())
pokemonObtain("Sharpedo",getBadge(),1," by evolving Carvanha.",getTotalPokemonCount())
pokemonObtain("Luvdisc",getBadge(),1," by fishing with a Good Rod (on Route 11, Fallshore City, Epidemy Town).",getTotalPokemonCount())
pokemonObtain("Barboach",getBadge(),1," by fishing with a Good Rod (on Route 11, Epidemy Town, Grim Woods).",getTotalPokemonCount())
pokemonObtain("Whiscash",getBadge(),1," by evolving Barboach.",getTotalPokemonCount())
pokemonObtain("Psyduck",getBadge(),1," by fishing with a Good Rod (Grim Woods, Valley Cave).",getTotalPokemonCount())
pokemonObtain("Golduck",getBadge(),1," by evolving Psyduck.",getTotalPokemonCount())
pokemonObtain("Finneon",getBadge(),1," by fishing with a Good Rod (Valley Cave).",getTotalPokemonCount())
pokemonObtain("Lumineon",getBadge(),1," by evolving Finneon.",getTotalPokemonCount())

// Thundercap Mtn 1F
pokemonObtain("Magnemite",getBadge(),1," at Thundercap Mtn 1F.",getTotalPokemonCount())
pokemonObtain("Magneton",getBadge(),1," at Thundercap Mtn 1F or by evolving Magnemite.",getTotalPokemonCount())
pokemonObtain("Magnezone",getBadge(),2," by evolving Magneton (Thunder Stone or level up at Thundercap Mtn).",getTotalPokemonCount())
pokemonObtain("Cubone",getBadge(),1," at Thundercap Mtn 1F.",getTotalPokemonCount())
achievement(
    title = "Marowak", description = "Obtain Marowak by evolving Cubone.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Marowak",getBadge(),0x069,getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Marowak", description = "Obtain Alolan Marowak by evolving Cubone at night.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Alolan Marowak",getBadge(),0x40f,getTotalPokemonCount()))
    )
)
pokemonObtain("Klink",getBadge(),1," at Thundercap Mtn 1F.",getTotalPokemonCount())
pokemonObtain("Klang",getBadge(),1," by evolving Klink.",getTotalPokemonCount())
pokemonObtain("Klinklang",getBadge(),1," by evolving Klang.",getTotalPokemonCount())
pokemonObtain("Elekid",getBadge(),1," at Thundercap Mtn 1F.",getTotalPokemonCount())
pokemonObtain("Electabuzz",getBadge(),1," at Thundercap Mtn 1F or by evolving Elekid.",getTotalPokemonCount())
pokemonObtain("Electivire",getBadge(),2," by evolving Electabuzz (obtain Electirizer from Electabuzz).",getTotalPokemonCount())
pokemonObtain("Tynamo",getBadge(),1," at Thundercap Mtn 1F.",getTotalPokemonCount())
pokemonObtain("Eelektrik",getBadge(),1," by evolving Tynamo.",getTotalPokemonCount())
pokemonObtain("Eelektross",getBadge(),1," by evolving Eelektrik (Thunder Stone).",getTotalPokemonCount())
pokemonObtain("Joltik",getBadge(),1," at Thundercap Mtn (swarm).",getTotalPokemonCount())
pokemonObtain("Galvantula",getBadge(),1," by evolving Joltik.",getTotalPokemonCount())
pokemonObtain("Ferroseed",getBadge(),1," at Thundercap Mtn (swarm).",getTotalPokemonCount())
pokemonObtain("Ferrothorn",getBadge(),1," by evolving Ferroseed.",getTotalPokemonCount())

// Cliff Cave
pokemonObtain("Machop",getBadge(),1," at Cliff Cave.",getTotalPokemonCount())
pokemonObtain("Machoke",getBadge(),1," at Cliff Cave or by evolving Machop.",getTotalPokemonCount())
pokemonObtain("Machamp",getBadge(),2," by evolving Machoke (Link Stone).",getTotalPokemonCount())
pokemonObtain("Wooper",getBadge(),1," at Cliff Cave.",getTotalPokemonCount())
pokemonObtain("Quagsire",getBadge(),1," at Cliff Cave or by evolving Wooper.",getTotalPokemonCount())
pokemonObtain("Misdreavus",getBadge(),1," at Cliff Cave.",getTotalPokemonCount())
pokemonObtain("Mismagius",getBadge(),2," by evolving Misdreavus (Dusk Stone).",getTotalPokemonCount())
achievement(
    title = "Alolan Geodude", description = "Obtain Alolan Geodude at Cliff Cave.", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Alolan Geodude",getBadge(),0x407,getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Graveler", description = "Obtain Alolan Graveler at Cliff Cave or by evolving Alolan Geodude.", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Alolan Graveler",getBadge(),0x408,getTotalPokemonCount()) ||
        evolve("Alolan Graveler",getBadge(),0x408,getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Golem", description = "Obtain Alolan Golem by evolving Alolan Graveler.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Alolan Golem",getBadge(),0x409,getTotalPokemonCount()))
    )
)

// Other
pokemonObtain("Tyrogue",getBadge(),1," by breeding Hitmontop.",getTotalPokemonCount())
pokemonObtain("Hitmontop",getBadge(),1," by trading a Lickitung with the Fighter Girl in Epidemy Town.",getTotalPokemonCount())
pokemonObtain("Hitmonlee",getBadge(),1," by evolving Tyrogue.",getTotalPokemonCount())
pokemonObtain("Hitmonchan",getBadge(),1," by evolving Tyrogue.",getTotalPokemonCount())
pokemonObtain("Togepi",getBadge(),1," as an Egg received from old lady in Fallshore City.",getTotalPokemonCount())
pokemonObtain("Togetic",getBadge(),1," by evolving Togepi.",getTotalPokemonCount())
pokemonObtain("Togekiss",getBadge(),2," by evolving Togetic (Shiny Stone).",getTotalPokemonCount())
achievement(
    title = "Hisuian Avalugg", description = "Obtain Hisuian Avalugg by evolving Bergmite (Hisui Rock).", points = 2,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Avalugg",getBadge(),0x4e1,getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Samurott I", description = "If possible, obtain Hisuian Samurott by evolving Dewott (Hisui Rock).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Samurott",getBadge(),0x4d9,getTotalPokemonCount())) || ((pokedex["Snivy"] == 1 || pokedex["Tepig"] == 1) && badges["Wings"] == 1 && AreaLocation() == 0x00b5)
    ) && badges["Battery"] != 1
)

function getTotalPokemonCount() => 352
unlockBadge(getBadge(), "Mel", 0x0022, getTotalPokemonCount(), " (+11 or 12 variations, max 354 registered).", "at least ")
leaderboard(
    getBadge() + " Badge Speedrun",
    "Fastest in-game time to obtain the " + getBadge() + " Badge with at least " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x0022, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Badge 5

function getBadge() => "Battery"

pokemonObtain("Dusknoir",getBadge(),1," by evolving Dusclops (Reaper Cloth).",getTotalPokemonCount())
pokemonObtain("Heatmor",getBadge(),1," at the Cinder Volcano Shadow Basement or Raid Den.",getTotalPokemonCount())
pokemonObtain("Mime Jr.",getBadge(),1," by breeding Mr. Mime with an Odd Incense.",getTotalPokemonCount())
pokemonObtain("Weavile",getBadge(),2," by evolving Sneasel (while holding a Razor Claw).",getTotalPokemonCount())

// Thundercap Mtn
pokemonObtain("Timburr",getBadge(),1," at Thundercap Mtn 2F, 4F.",getTotalPokemonCount())
pokemonObtain("Gurdurr",getBadge(),1," by evolving Timburr.",getTotalPokemonCount())
pokemonObtain("Conkeldurr",getBadge(),1," by evolving Gurdurr (Link Stone).",getTotalPokemonCount())
pokemonObtain("Chinchou",getBadge(),1," by fishing with the Good Rod in Thundercap Mtn.",getTotalPokemonCount())
pokemonObtain("Lanturn",getBadge(),1," by evolving Chinchou.",getTotalPokemonCount())

// Route 12
pokemonObtain("Fletchling",getBadge(),1," on Route 12 (day).",getTotalPokemonCount())
pokemonObtain("Fletchinder",getBadge(),1," on Route 12 (day) or by evolving Fletchling.",getTotalPokemonCount())
pokemonObtain("Talonflame",getBadge(),1," by evolving Fletchinder.",getTotalPokemonCount())
pokemonObtain("Rockruff",getBadge(),1," on Route 12.",getTotalPokemonCount())
pokemonObtain("Lycanroc",getBadge(),1," by evolving Rockruff.",getTotalPokemonCount())
pokemonObtain("Ponyta",getBadge(),1," on Route 12.",getTotalPokemonCount())
pokemonObtain("Rapidash",getBadge(),1," by evolving Ponyta.",getTotalPokemonCount())
pokemonObtain("Snubbull",getBadge(),1," on Route 12.",getTotalPokemonCount())
pokemonObtain("Granbull",getBadge(),1," by evolving Snubbull.",getTotalPokemonCount())
pokemonObtain("Mienfoo",getBadge(),1," on Route 12.",getTotalPokemonCount())
pokemonObtain("Mienshao",getBadge(),1," by evolving Mienfoo.",getTotalPokemonCount())
pokemonObtain("Dedenne",getBadge(),1," on Route 12.",getTotalPokemonCount())
pokemonObtain("Gothita",getBadge(),1," on Route 12 (night).",getTotalPokemonCount())
pokemonObtain("Gothorita",getBadge(),1," by evolving Gothita.",getTotalPokemonCount())
pokemonObtain("Gothitelle",getBadge(),1," by evolving Gothorita.",getTotalPokemonCount())
pokemonObtain("Solosis",getBadge(),1," on Route 12 (day).",getTotalPokemonCount())
pokemonObtain("Duosion",getBadge(),1," by evolving Solosis.",getTotalPokemonCount())
pokemonObtain("Reuniclus",getBadge(),1," by evolving Duosion.",getTotalPokemonCount())
pokemonObtain("Swirlix",getBadge(),1," on Route 12 (swarm).",getTotalPokemonCount())
pokemonObtain("Slurpuff",getBadge(),2," at the Route 12 Raid Den or by evolving Swirlix (Whipped Dream).",getTotalPokemonCount())
pokemonObtain("Spritzee",getBadge(),1," on Route 12 (swarm).",getTotalPokemonCount())
pokemonObtain("Aromatisse",getBadge(),2," at the Route 12 Raid Den or by evolving Spritzee (Sachet).",getTotalPokemonCount())
pokemonObtain("Wailmer",getBadge(),1," by fishing with the Good Rod (on Route 12).",getTotalPokemonCount())
pokemonObtain("Wailord",getBadge(),1," by evolving Wailmer.",getTotalPokemonCount())

// Dehara Game Corner
pokemonObtain("Eevee",getBadge(),1," at the Dehara Game Corner.",getTotalPokemonCount())
pokemonObtain("Vaporeon",getBadge(),1," by evolving Eevee (Water Stone).",getTotalPokemonCount())
pokemonObtain("Jolteon",getBadge(),1," by evolving Eevee (Thunder Stone).",getTotalPokemonCount())
pokemonObtain("Flareon",getBadge(),1," by evolving Eevee (Fire Stone).",getTotalPokemonCount())
pokemonObtain("Espeon",getBadge(),1," by evolving Eevee (Max Happiness at day).",getTotalPokemonCount())
pokemonObtain("Umbreon",getBadge(),1," by evolving Eevee (Max Happiness at night).",getTotalPokemonCount())
pokemonObtain("Leafeon",getBadge(),1," by evolving Eevee (Leaf Stone).",getTotalPokemonCount())
pokemonObtain("Glaceon",getBadge(),1," by evolving Eevee (Ice Stone).",getTotalPokemonCount())
pokemonObtain("Sylveon",getBadge(),1," by evolving Eevee (Level-Up while knowing a Fairy-type move with max happiness).",getTotalPokemonCount())
pokemonObtain("Axew",getBadge(),2," at the Dehara Game Corner.",getTotalPokemonCount())
pokemonObtain("Fraxure",getBadge(),1," by evolving Axew.",getTotalPokemonCount())
pokemonObtain("Haxorus",getBadge(),1," by evolving Fraxure.",getTotalPokemonCount())
pokemonObtain("Porygon",getBadge(),2," at the Dehara Game Corner.",getTotalPokemonCount())
pokemonObtain("Porygon2",getBadge(),1," by evolving Porygon (Up-Grade).",getTotalPokemonCount())
pokemonObtain("Emolga",getBadge(),1," at the Dehara Game Corner.",getTotalPokemonCount())
pokemonObtain("Hawlucha",getBadge(),1," at the Dehara Game Corner.",getTotalPokemonCount())
pokemonObtain("Klefki",getBadge(),1," at the Dehara Game Corner.",getTotalPokemonCount())

// Rift Cave, Ruins of Void
pokemonObtain("Golett",getBadge(),1," at the Rift Cave 1F.",getTotalPokemonCount())
pokemonObtain("Golurk",getBadge(),1," by evolving Golett.",getTotalPokemonCount())
pokemonObtain("Chimecho",getBadge(),1," at the Rift Cave.",getTotalPokemonCount())
pokemonObtain("Horsea",getBadge(),1," by fishing with a Good Rod at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Seadra",getBadge(),1," by evolving Horsea.",getTotalPokemonCount())
pokemonObtain("Kingdra",getBadge(),2," by evolving Seadra (obtain Dragon Scale from Horsea).",getTotalPokemonCount())
pokemonObtain("Baltoy",getBadge(),1," at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Claydol",getBadge(),1," at the Ruins of Void B1F,B2F or by evolving Baltoy.",getTotalPokemonCount())
pokemonObtain("Yamask",getBadge(),1," at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Cofagrigus",getBadge(),1," at the Ruins of Void or by evolving Yamask.",getTotalPokemonCount())
pokemonObtain("Sableye",getBadge(),1," at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Lunatone",getBadge(),1," at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Solrock",getBadge(),1," at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Sigilyph",getBadge(),1," at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Pichu",getBadge(),1," by breeding Pikachu.",getTotalPokemonCount())
pokemonObtain("Pikachu",getBadge(),2," as a reward from A Life of No Regrets.",getTotalPokemonCount())
achievement(
    title = "Raichu", description = "Obtain Raichu by evolving Pikachu (non-Balloon).", points = 2,
    trigger = (
    (
        always_false() || 
        evolve("Raichu",getBadge(),0x01a,getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Raichu", description = "Obtain Alolan Raichu by evolving Pikachu by using a Thunder Stone while standing on the seashore with water splashing under your feet.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Alolan Raichu",getBadge(),0x3fe,getTotalPokemonCount()))
    )
)
pokemonObtain("Munna",getBadge(),2," at the Tarmigan Town Raid Den.",getTotalPokemonCount())
pokemonObtain("Musharna",getBadge(),1," by evolving Munna (Moon Stone).",getTotalPokemonCount())
pokemonObtain("Pachirisu",getBadge(),1," by trading a Manectric with a guy in Tarmigan Town.",getTotalPokemonCount())
achievement(
    title = "Sinnoh Starters I", 
    description = "Obtain either Turtwig, Chimchar, or Piplup from a girl in Dehara City.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Turtwig",getBadge(),getTotalPokemonCount()) ||
        obtain("Chimchar",getBadge(),getTotalPokemonCount()) ||
        obtain("Piplup",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Sinnoh Starters II", 
    description = "Evolve your Sinnoh starter to become either Grotle, Monferno, or Prinplup.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Grotle",getBadge(),getTotalPokemonCount()) ||
        obtain("Monferno",getBadge(),getTotalPokemonCount()) ||
        obtain("Prinplup",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Sinnoh Starters III", 
    description = "Evolve your Sinnoh starter to their final form as either Torterra, Infernape, or Empoleon.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Torterra",getBadge(),getTotalPokemonCount()) ||
        obtain("Infernape",getBadge(),getTotalPokemonCount()) ||
        obtain("Empoleon",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Unova Starters IV", 
    description = "Obtain either Snivy, Tepig, or Oshawott from a girl on Route 5.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Snivy",getBadge(),getTotalPokemonCount()) ||
        obtain("Tepig",getBadge(),getTotalPokemonCount()) ||
        obtain("Oshawott",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Unova Starters V", 
    description = "Evolve your second Unova starter to become either Servine, Pignite, or Dewott.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Servine",getBadge(),getTotalPokemonCount()) ||
        obtain("Pignite",getBadge(),getTotalPokemonCount()) ||
        obtain("Dewott",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Unova Starters VI", 
    description = "Evolve your second Unova starter to their final form as either Serperior, Emboar, or Samurott.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Serperior",getBadge(),getTotalPokemonCount()) ||
        obtain("Emboar",getBadge(),getTotalPokemonCount()) ||
        obtain("Samurott",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Samurott II", description = "If possible, obtain Hisuian Samurott by evolving Dewott (Hisui Rock).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Samurott",getBadge(),0x4d9,getTotalPokemonCount()) || (pokedex["Snivy"] == 1 && pokedex["Tepig"] == 1) ||
        pokedex["Samurott"] == 1 && AreaLocation() == 0x0022 && badges["Fall"] > prev(badges["Fall"]))
    )
)

function getTotalPokemonCount() => 428
unlockBadge(getBadge(), "Galavan", 0x009d, getTotalPokemonCount(), " (+12 or 13 variations, max 430 registered).", "at least ")
leaderboard(
    getBadge() + " Badge Speedrun",
    "Fastest in-game time to obtain the " + getBadge() + " Badge with at least " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x009d, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Badge 6

function getBadge() => "Ring"

pokemonObtain("Chingling",getBadge(),1," by breeding Chimecho with a Pure Essence (gift in Vivill Town).",getTotalPokemonCount())

// Surfing or Fishing
pokemonObtain("Tentacool",getBadge(),1," by surfing pretty much anywhere.",getTotalPokemonCount())
pokemonObtain("Tentacruel",getBadge(),1," by surfing pretty much anywhere or by evolving Tentacool.",getTotalPokemonCount())
pokemonObtain("Lapras",getBadge(),1," by surfing (Icicle Cave, Frost Mountain).",getTotalPokemonCount())
pokemonObtain("Basculin",getBadge(),1," by surfing (on Routes 2, 4, 5 ,11 ,15, Dresco Town, Vivill Town, Vivill Warehouse).",getTotalPokemonCount())
pokemonObtain("Mantyke",getBadge(),1," by surfing (on Routes 6, 7, 12, 16, 17, Antisis City).",getTotalPokemonCount())
pokemonObtain("Mantine",getBadge(),1," by surfing (on Routes 14, 18, Gurun Town, at the Ruins of Void) or by evolving Mantyke (Level-Up with a Remoraid in your party).",getTotalPokemonCount())
pokemonObtain("Pyukumuku",getBadge(),1," by surfing (Fallshore City, Dehara City).",getTotalPokemonCount())
pokemonObtain("Stunfisk",getBadge(),1," by surfing (Thundercap Mtn, Polder Town).",getTotalPokemonCount())
pokemonObtain("Alomomola",getBadge(),1," by surfing (on Route 13).",getTotalPokemonCount())
pokemonObtain("Skrelp",getBadge(),1," by fishing with a Good Rod (on Route 13).",getTotalPokemonCount())
pokemonObtain("Dragalge",getBadge(),1," by evolving Skrelp.",getTotalPokemonCount())
pokemonObtain("Clauncher",getBadge(),1," by fishing with a Good Rod (on Route 13).",getTotalPokemonCount())
pokemonObtain("Clawitzer",getBadge(),1," by evolving Clauncher.",getTotalPokemonCount())
pokemonObtain("Corsola",getBadge(),1," by fishing with a Good Rod (on Route 16, Gurun Town).",getTotalPokemonCount())

// Route 14
pokemonObtain("Bellsprout",getBadge(),1," on Route 14 (day).",getTotalPokemonCount())
pokemonObtain("Weepinbell",getBadge(),1," on Route 14 (day) or by evolving Bellsprout.",getTotalPokemonCount())
pokemonObtain("Victreebel",getBadge(),1," by evolving Weepinbell (Leaf Stone).",getTotalPokemonCount())
pokemonObtain("Oddish",getBadge(),1," on Route 14 (night).",getTotalPokemonCount())
pokemonObtain("Gloom",getBadge(),1," on Route 14 (night) or by evolving Oddish.",getTotalPokemonCount())
pokemonObtain("Vileplume",getBadge(),1," by evolving Gloom (Leaf Stone).",getTotalPokemonCount())
pokemonObtain("Bellossom",getBadge(),1," by evolving Gloom (Sun Stone).",getTotalPokemonCount())

// Great Desert
pokemonObtain("Dwebble",getBadge(),1," at the Great Desert.",getTotalPokemonCount())
pokemonObtain("Crustle",getBadge(),1," by evolving Dwebble.",getTotalPokemonCount())
pokemonObtain("Sandile",getBadge(),1," by breeding Krokorok or Krookodile.",getTotalPokemonCount())
pokemonObtain("Krokorok",getBadge(),1," at the Great Desert.",getTotalPokemonCount())
pokemonObtain("Krookodile",getBadge(),1," by evolving Krokorok.",getTotalPokemonCount())
pokemonObtain("Cacnea",getBadge(),1," at the Great Desert.",getTotalPokemonCount())
pokemonObtain("Cacturne",getBadge(),1," by evolving Cacnea.",getTotalPokemonCount())
pokemonObtain("Darumaka",getBadge(),1," at the Great Desert.",getTotalPokemonCount())
pokemonObtain("Darmanitan",getBadge(),1," by evolving Darumaka.",getTotalPokemonCount())
pokemonObtain("Hippopotas",getBadge(),1," at the Great Desert.",getTotalPokemonCount())
pokemonObtain("Hippowdon",getBadge(),1," by evolving Hippopotas.",getTotalPokemonCount())
pokemonObtain("Trapinch",getBadge(),1," by breeding Vibrava or Flygon.",getTotalPokemonCount())
pokemonObtain("Vibrava",getBadge(),1," at the Great Desert.",getTotalPokemonCount())
pokemonObtain("Flygon",getBadge(),1," by evolving Vibrava.",getTotalPokemonCount())
pokemonObtain("Maractus",getBadge(),1," at the Great Desert.",getTotalPokemonCount())
achievement(
    title = "Sandshrew", description = "Obtain Sandshrew by breeding Sandslash.", points = 1,
    trigger = (
    (
        always_false() || 
        hatch("Sandshrew",getBadge(),0x01b,getTotalPokemonCount()))
    )
)
achievement(
    title = "Sandslash", description = "Obtain Sandslash at the Great Desert.", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Sandslash",getBadge(),0x01c,getTotalPokemonCount()))
    )
)
pokemonObtain("Shieldon",getBadge(),1," at the Great Desert (Rock Smash, Armor Fossil).",getTotalPokemonCount())
pokemonObtain("Bastiodon",getBadge(),1," by evolving Shieldon.",getTotalPokemonCount())
pokemonObtain("Anorith",getBadge(),1," at the Great Desert (Rock Smash, Claw Fossil).",getTotalPokemonCount())
pokemonObtain("Armaldo",getBadge(),1," by evolving Anorith.",getTotalPokemonCount())
pokemonObtain("Tirtouga",getBadge(),1," at the Great Desert (Rock Smash, Cover Fossil).",getTotalPokemonCount())
pokemonObtain("Carracosta",getBadge(),1," by evolving Tirtouga.",getTotalPokemonCount())
pokemonObtain("Kabuto",getBadge(),1," at the Great Desert (Rock Smash, Dome Fossil).",getTotalPokemonCount())
pokemonObtain("Kabutops",getBadge(),1," by evolving Kabuto.",getTotalPokemonCount())
pokemonObtain("Omanyte",getBadge(),1," at the Great Desert (Rock Smash, Helix Fossil).",getTotalPokemonCount())
pokemonObtain("Omastar",getBadge(),1," by evolving Omanyte.",getTotalPokemonCount())
pokemonObtain("Tyrunt",getBadge(),1," at the Great Desert (Rock Smash, Jaw Fossil).",getTotalPokemonCount())
pokemonObtain("Tyrantrum",getBadge(),1," by evolving Tyrunt.",getTotalPokemonCount())
pokemonObtain("Aerodactyl",getBadge(),1," at the Great Desert (Rock Smash, Old Amber).",getTotalPokemonCount())
pokemonObtain("Archen",getBadge(),1," at the Great Desert (Rock Smash, Plume Fossil).",getTotalPokemonCount())
pokemonObtain("Archeops",getBadge(),1," by evolving Archen.",getTotalPokemonCount())
pokemonObtain("Lileep",getBadge(),1," at the Great Desert (Rock Smash, Root Fossil).",getTotalPokemonCount())
pokemonObtain("Cradily",getBadge(),1," by evolving Lileep.",getTotalPokemonCount())
pokemonObtain("Amaura",getBadge(),1," at the Great Desert (Rock Smash, Sail Fossil).",getTotalPokemonCount())
pokemonObtain("Aurorus",getBadge(),1," by evolving Amaura.",getTotalPokemonCount())
pokemonObtain("Cranidos",getBadge(),1," at the Great Desert (Rock Smash, Skull Fossil).",getTotalPokemonCount())
pokemonObtain("Rampardos",getBadge(),1," by evolving Cranidos.",getTotalPokemonCount())
pokemonObtain("Rufflet",getBadge(),1," by finding in the Great Desert (Monday or Tuesday).",getTotalPokemonCount())
achievement(
    title = "Braviary", description = "Obtain Braviary by evolving Rufflet.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Braviary",getBadge(),0x2a9,getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Braviary", description = "Obtain Hisuian Braviary by evolving Rufflet (Hisui Rock).", points = 2,
    trigger = (
    (
        always_false() || 
        evolve("Hisuian Braviary",getBadge(),0x4de,getTotalPokemonCount()))
    )
)
pokemonObtain("Vullaby",getBadge(),1," by finding in the Great Desert (Monday or Tuesday).",getTotalPokemonCount())
pokemonObtain("Mandibuzz",getBadge(),1," by evolving Vullaby.",getTotalPokemonCount())

// Vivill
pokemonObtain("Wurmple",getBadge(),1," at Vivill Woods.",getTotalPokemonCount())
pokemonObtain("Silcoon",getBadge(),1," at Vivill Woods or by evolving Wurmple.",getTotalPokemonCount())
pokemonObtain("Beautifly",getBadge(),1," by evolving Silcoon.",getTotalPokemonCount())
pokemonObtain("Cascoon",getBadge(),1," at Vivill Woods or by evolving Wurmple.",getTotalPokemonCount())
pokemonObtain("Dustox",getBadge(),1," by evolving Cascoon.",getTotalPokemonCount())
pokemonObtain("Scatterbug",getBadge(),1," at Vivill Woods.",getTotalPokemonCount())
pokemonObtain("Spewpa",getBadge(),1," at Vivill Woods or by evolving Scatterbug.",getTotalPokemonCount())
pokemonObtain("Vivillon",getBadge(),1," by evolving Spewpa.",getTotalPokemonCount())
pokemonObtain("Cottonee",getBadge(),1," at Vivill Woods.",getTotalPokemonCount())
pokemonObtain("Whimsicott",getBadge(),1," by evolving Cottonee (Sun Stone).",getTotalPokemonCount())
pokemonObtain("Petilil",getBadge(),1," at Vivill Woods.",getTotalPokemonCount())
achievement(
    title = "Lilligant", description = "Obtain Lilligant by evolving Petilil (Sun Stone).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Lilligant",getBadge(),0x25a,getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Lilligant", description = "Obtain Hisuian Lilligant by evolving Petilil (Sun Stone and Hisui Rock).", points = 2,
    trigger = (
    (
        always_false() || 
        evolve("Hisuian Lilligant",getBadge(),0x4da,getTotalPokemonCount()))
    )
)
pokemonObtain("Paras",getBadge(),1," at Vivill Woods (mushroom).",getTotalPokemonCount())
pokemonObtain("Parasect",getBadge(),1," by evolving Paras.",getTotalPokemonCount())
pokemonObtain("Foongus",getBadge(),1," at Vivill Woods (mushroom, Trainer ID dependant) or by breeding Amoonguss.",getTotalPokemonCount())
pokemonObtain("Amoonguss",getBadge(),1," by evolving Foongus or by trading a Shiinotic in Vivill Town.",getTotalPokemonCount())
pokemonObtain("Morelull",getBadge(),1," at Vivill Woods (mushroom, Trainer ID dependant) or by breeding Shiinotic.",getTotalPokemonCount())
pokemonObtain("Shiinotic",getBadge(),1," by evolving Morelull or by trading an Amoongus in Vivill Town.",getTotalPokemonCount())
pokemonObtain("Sewaddle",getBadge(),1," by breeding Swadloon or Leavanny.",getTotalPokemonCount())
pokemonObtain("Swadloon",getBadge(),1," at Vivill Woods.",getTotalPokemonCount())
pokemonObtain("Leavanny",getBadge(),1," by evolving Swadloon.",getTotalPokemonCount())

// Route 16
pokemonObtain("Tangela",getBadge(),1," on Route 16 or at the Route 16 Raid Den.",getTotalPokemonCount())
pokemonObtain("Tangrowth",getBadge(),1," by evolving Tangela (while knowing Ancient Power).",getTotalPokemonCount())
pokemonObtain("Girafarig",getBadge(),1," on Route 16 or at the Route 16 Raid Den.",getTotalPokemonCount())
pokemonObtain("Pancham",getBadge(),1," on Route 16.",getTotalPokemonCount())
pokemonObtain("Pangoro",getBadge(),1," by evolving Pancham or at the Route 16 Raid Den.",getTotalPokemonCount())
pokemonObtain("Pawniard",getBadge(),1," on Route 16 or at the Route 16 Raid Den.",getTotalPokemonCount())
pokemonObtain("Bisharp",getBadge(),1," by evolving Pawniard.",getTotalPokemonCount())
pokemonObtain("Chatot",getBadge(),1," on Route 16 or at the Route 16 Raid Den.",getTotalPokemonCount())
pokemonObtain("Throh",getBadge(),1," on Route 16 or at the Route 16 Raid Den.",getTotalPokemonCount())
pokemonObtain("Sawk",getBadge(),1," on Route 16 or at the Route 16 Raid Den.",getTotalPokemonCount())
pokemonObtain("Kecleon",getBadge(),1," on Route 16 (invisible).",getTotalPokemonCount())

// Antisis
achievement(
    title = "Grimer", description = "Obtain Grimer at the Antisis Sewers.", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Grimer",getBadge(),0x058,getTotalPokemonCount()))
    )
)
achievement(
    title = "Muk", description = "Obtain Muk at the Antisis Sewers or by evolving Grimer.", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Muk",getBadge(),0x059,getTotalPokemonCount()) ||
        evolve("Muk",getBadge(),0x059,getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Grimer", description = "Obtain Alolan Grimer by completing Supply and Demand.", points = 2,
    trigger = (
    (
        always_false() || 
        hatch("Alolan Grimer",getBadge(),0x40a,getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Muk", description = "Obtain Alolan Muk by evolving Alolan Grimer.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Alolan Muk",getBadge(),0x40b,getTotalPokemonCount()))
    )
)
pokemonObtain("Koffing",getBadge(),1," at the Antisis Sewers or by breeding Weezing.",getTotalPokemonCount())
pokemonObtain("Weezing",getBadge(),1," at the Antisis Sewers.",getTotalPokemonCount())
pokemonObtain("Venipede",getBadge(),1," by breeding Whirlipede or Scolipede.",getTotalPokemonCount())
pokemonObtain("Whirlipede",getBadge(),1," at the Antisis Sewers (swarm).",getTotalPokemonCount())
pokemonObtain("Scolipede",getBadge(),1," by evolving Whirlipede.",getTotalPokemonCount())
pokemonObtain("Trubbish",getBadge(),1," in a Dumpster in Antisis City.",getTotalPokemonCount())
pokemonObtain("Garbodor",getBadge(),1," in a Dumpster in Antisis City or by evolving Trubbish.",getTotalPokemonCount())

// Lost Tunnel
pokemonObtain("Diglett",getBadge(),2," at the Lost Tunnel (start the Island Saviour mission).",getTotalPokemonCount())
pokemonObtain("Dugtrio",getBadge(),1," at the Lost Tunnel (start the Island Saviour mission) or by evolving Diglett.",getTotalPokemonCount())

// Other
pokemonObtain("Type: Null",getBadge(),2," by completing 20 Missions.",getTotalPokemonCount())
pokemonObtain("Silvally",getBadge(),1," by evolving Type: Null.",getTotalPokemonCount())

function getTotalPokemonCount() => 535
unlockBadge(getBadge(), "Big Mo", 0x0014, getTotalPokemonCount(), " (+18 or 19 variations, max 537 registered).", "at least ")
leaderboard(
    getBadge() + " Badge Speedrun",
    "Fastest in-game time to obtain the " + getBadge() + " Badge with at least " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x0014, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Badge 7

function getBadge() => "Swamp"

// Route 17
pokemonObtain("Hoppip",getBadge(),1," by breeding Skiploom or Jumpluff.",getTotalPokemonCount())
pokemonObtain("Skiploom",getBadge(),1," on Route 17 (day).",getTotalPokemonCount())
pokemonObtain("Jumpluff",getBadge(),1," by evolving Jumpluff.",getTotalPokemonCount())
pokemonObtain("Tropius",getBadge(),1," on Route 17 (day).",getTotalPokemonCount())
pokemonObtain("Pidgey",getBadge(),1," by breeding Pidgeotto or Pidgeot.",getTotalPokemonCount())
pokemonObtain("Pidgeotto",getBadge(),1," on Route 17 (day).",getTotalPokemonCount())
pokemonObtain("Pidgeot",getBadge(),1," by evolving Pidgeotto.",getTotalPokemonCount())
pokemonObtain("Zangoose",getBadge(),1," on Route 17.",getTotalPokemonCount())
pokemonObtain("Seviper",getBadge(),1," on Route 17.",getTotalPokemonCount())
pokemonObtain("Bagon",getBadge(),1," on Route 17.",getTotalPokemonCount())
pokemonObtain("Shelgon",getBadge(),1," by evolving Bagon.",getTotalPokemonCount())
pokemonObtain("Salamence",getBadge(),1," by evolving Shelgon.",getTotalPokemonCount())
pokemonObtain("Volbeat",getBadge(),1," on Route 17 (swarm).",getTotalPokemonCount())
pokemonObtain("Illumise",getBadge(),1," on Route 17 (swarm).",getTotalPokemonCount())

// Cootes Bog
pokemonObtain("Croagunk",getBadge(),1," at Cootes Bog or by breeding Toxicroak.",getTotalPokemonCount())
pokemonObtain("Toxicroak",getBadge(),1," at Cootes Bog.",getTotalPokemonCount())
pokemonObtain("Totodile",getBadge(),1," by breeding Croconaw or Feraligatr.",getTotalPokemonCount())
pokemonObtain("Croconaw",getBadge(),1," at Cootes Bog (swarm).",getTotalPokemonCount())
pokemonObtain("Feraligatr",getBadge(),2," by evolving Croconaw or by completing the Protector of the Swamp mission.",getTotalPokemonCount())
pokemonObtain("Carnivine",getBadge(),1," at Cootes Bog.",getTotalPokemonCount())

// Magnolia Fields
pokemonObtain("Miltank",getBadge(),1," at the Magnolia Fields.",getTotalPokemonCount())
pokemonObtain("Pidove",getBadge(),1," by breeding Tranquill or Unfezant or purchase as a random egg from the Day-Care Man's Sister.",getTotalPokemonCount())
pokemonObtain("Tranquill",getBadge(),1," at the Magnolia Fields.",getTotalPokemonCount())
pokemonObtain("Unfezant",getBadge(),1," by evolving Tranquill.",getTotalPokemonCount())
pokemonObtain("Skiddo",getBadge(),1," by breeding Gogoat.",getTotalPokemonCount())
pokemonObtain("Gogoat",getBadge(),1," at the Magnolia Fields.",getTotalPokemonCount())
pokemonObtain("Mudbray",getBadge(),1," by breeding Mudsdale.",getTotalPokemonCount())
pokemonObtain("Mudsdale",getBadge(),1," at the Magnolia Fields.",getTotalPokemonCount())
pokemonObtain("Furfrou",getBadge(),1," at the Magnolia Fields.",getTotalPokemonCount())
pokemonObtain("Cyndaquil",getBadge(),1," by breeding Quilava or Typhlosion.",getTotalPokemonCount())
pokemonObtain("Quilava",getBadge(),1," at the Magnolia Fields (swarm).",getTotalPokemonCount())
achievement(
    title = "Typhlosion", description = "Obtain Typhlosion by evolving Quilava.", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Typhlosion",getBadge(),0x09d,getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Typhlosion", description = "Obtain Hisuian Typhlosion by evolving Quilava (Hisui Rock).", points = 2,
    trigger = (
    (
        always_false() || 
        evolve("Hisuian Typhlosion",getBadge(),0x4d6,getTotalPokemonCount()))
    )
)

// Safari Zone
pokemonObtain("Rhyhorn",getBadge(),1," at the Safari Zone (Easy or Medium).",getTotalPokemonCount())
pokemonObtain("Rhydon",getBadge(),1," at the Safari Zone (Hard or Insane) or by evolving Rhyhorn.",getTotalPokemonCount())
pokemonObtain("Treecko",getBadge(),1," at the Safari Zone (Easy or Medium).",getTotalPokemonCount())
pokemonObtain("Grovyle",getBadge(),1," at the Safari Zone (Hard or Insane) or by evolving Treecko.",getTotalPokemonCount())
pokemonObtain("Sceptile",getBadge(),1," by evolving Grovyle.",getTotalPokemonCount())
pokemonObtain("Torchic",getBadge(),1," at the Safari Zone (Easy or Medium).",getTotalPokemonCount())
pokemonObtain("Combusken",getBadge(),1," at the Safari Zone (Hard or Insane) or by evolving Torchic.",getTotalPokemonCount())
pokemonObtain("Blaziken",getBadge(),1," by evolving Combusken.",getTotalPokemonCount())
pokemonObtain("Mudkip",getBadge(),1," at the Safari Zone (Easy or Medium).",getTotalPokemonCount())
pokemonObtain("Marshtomp",getBadge(),1," at the Safari Zone (Hard or Insane) or by evolving Mudkip.",getTotalPokemonCount())
pokemonObtain("Swampert",getBadge(),1," by evolving Marshtomp.",getTotalPokemonCount())
pokemonObtain("Helioptile",getBadge(),1," at the Safari Zone (Easy, Medium, Hard).",getTotalPokemonCount())
pokemonObtain("Heliolisk",getBadge(),1," at the Safari Zone (Insane) or by evolving Helioptile (Sun Stone).",getTotalPokemonCount())
pokemonObtain("Natu",getBadge(),1," at the Safari Zone (Easy).",getTotalPokemonCount())
pokemonObtain("Xatu",getBadge(),1," at the Safari Zone (Medium) or by evolving Natu.",getTotalPokemonCount())
pokemonObtain("Skitty",getBadge(),1," at the Safari Zone (Easy).",getTotalPokemonCount())
pokemonObtain("Delcatty",getBadge(),1," by evolving Skitty (Moon Stone).",getTotalPokemonCount())
pokemonObtain("Plusle",getBadge(),1," at the Safari Zone (Easy).",getTotalPokemonCount())
pokemonObtain("Minun",getBadge(),1," at the Safari Zone (Easy).",getTotalPokemonCount())
pokemonObtain("Blitzle",getBadge(),1," at the Safari Zone (Easy).",getTotalPokemonCount())
pokemonObtain("Zebstrika",getBadge(),1," at the Safari Zone (Medium, Hard) or by evolving Blitzle.",getTotalPokemonCount())
pokemonObtain("Bounsweet",getBadge(),1," at the Safari Zone (Easy).",getTotalPokemonCount())
pokemonObtain("Steenee",getBadge(),1," at the Safari Zone (Medium) or by evolving Bounsweet.",getTotalPokemonCount())
pokemonObtain("Tsareena",getBadge(),1," by evolving Steenee (Level-Up while knowing Stomp).",getTotalPokemonCount())
achievement(
    title = "Alolan Meowth", 
    description = "Obtain Alolan Meowth at the Safari Zone (Easy).", points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Meowth",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Persian", 
    description = "Obtain Alolan Persian by evolving Alolan Meowth (max happiness).", points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Persian",getBadge(),getTotalPokemonCount()))
    )
)
pokemonObtain("Kangaskhan",getBadge(),1," at the Safari Zone (Medium, Hard, Insane).",getTotalPokemonCount())
pokemonObtain("Tauros",getBadge(),1," at the Safari Zone (Medium, Hard, Insane).",getTotalPokemonCount())
pokemonObtain("Wynaut",getBadge(),1," by breeding Wobbuffet with a Lax Incense.",getTotalPokemonCount())
pokemonObtain("Wobbuffet",getBadge(),1," at the Safari Zone (Medium, Hard, Insane) or Magnolia Fields.",getTotalPokemonCount())
pokemonObtain("Spinda",getBadge(),1," at the Safari Zone (Medium, Hard).",getTotalPokemonCount())
achievement(
    title = "Alolan Diglett", description = "Obtain Alolan Diglett at the Safari Zone (Medium, Hard).", points = 1,
    trigger = (
    (
        always_false() || 
        catch_safari("Alolan Diglett",getBadge(),0x403,getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Dugtrio", description = "Obtain Alolan Dugtrio at the Safari Zone (Insane) or by evolving Alolan Diglett.", points = 1,
    trigger = (
    (
        always_false() || 
        catch_safari("Alolan Dugtrio",getBadge(),0x404,getTotalPokemonCount()) ||
        evolve("Alolan Dugtrio",getBadge(),0x404,getTotalPokemonCount()))
    )
)
pokemonObtain("Wimpod",getBadge(),1," by breeding Golisopod.",getTotalPokemonCount())
pokemonObtain("Golisopod",getBadge(),2," at the Safari Zone (Hard, Insane).",getTotalPokemonCount())
pokemonObtain("Honedge",getBadge(),1," by breeding Doublade or Aegislash.",getTotalPokemonCount())
pokemonObtain("Doublade",getBadge(),2," at the Safari Zone (Insane).",getTotalPokemonCount())
pokemonObtain("Aegislash",getBadge(),1," by evolving Doublade (Dusk Stone).",getTotalPokemonCount())
achievement(
    title = "Alolan Exeggutor", description = "Obtain Alolan Exeggutor by evolving Safari Zone Exeggcute (Leaf Stone).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Alolan Exeggutor",getBadge(),0x40d,getTotalPokemonCount()))
    )
)

// Fishing, Eggs
pokemonObtain("Bruxish",getBadge(),1," by fishing with a Super Rod (on Routes 9,10, Tehl Town, Auburn Waterway).",getTotalPokemonCount())
pokemonObtain("Dhelmise",getBadge(),1," by fishing with a Super Rod at the Vivill Warehouse.",getTotalPokemonCount())
pokemonObtain("Bulbasaur",getBadge(),1," as a free daily egg from the Day-Care Man's Sister.",getTotalPokemonCount())
pokemonObtain("Ivysaur",getBadge(),1," by evolving Bulbasaur.",getTotalPokemonCount())
pokemonObtain("Venusaur",getBadge(),1," by evolving Ivysaur.",getTotalPokemonCount())
pokemonObtain("Charmander",getBadge(),1," as a free daily egg from the Day-Care Man's Sister.",getTotalPokemonCount())
pokemonObtain("Charmeleon",getBadge(),1," by evolving Charmander.",getTotalPokemonCount())
pokemonObtain("Charizard",getBadge(),1," by evolving Charmeleon.",getTotalPokemonCount())
pokemonObtain("Squirtle",getBadge(),1," as a free daily egg from the Day-Care Man's Sister.",getTotalPokemonCount())
pokemonObtain("Wartortle",getBadge(),1," by evolving Squirtle.",getTotalPokemonCount())
pokemonObtain("Blastoise",getBadge(),1," by evolving Wartortle.",getTotalPokemonCount())
pokemonObtain("Chespin",getBadge(),1," as a free daily egg from the Day-Care Man's Sister.",getTotalPokemonCount())
pokemonObtain("Quilladin",getBadge(),1," by evolving Chespin.",getTotalPokemonCount())
pokemonObtain("Chesnaught",getBadge(),1," by evolving Quilladin.",getTotalPokemonCount())
pokemonObtain("Fennekin",getBadge(),1," as a free daily egg from the Day-Care Man's Sister.",getTotalPokemonCount())
pokemonObtain("Braixen",getBadge(),1," by evolving Fennekin.",getTotalPokemonCount())
pokemonObtain("Delphox",getBadge(),1," by evolving Braixen.",getTotalPokemonCount())
pokemonObtain("Deino",getBadge(),1," by purchasing as a random egg from the Day-Care Man's Sister.",getTotalPokemonCount())
pokemonObtain("Zweilous",getBadge(),1," by evolving Deino.",getTotalPokemonCount())
pokemonObtain("Hydreigon",getBadge(),1," by evolving Zweilous.",getTotalPokemonCount())
pokemonObtain("Feebas",getBadge(),2," as a reward from completing the Fisher Master mission.",getTotalPokemonCount())
pokemonObtain("Milotic",getBadge(),1," by evolving Feebas (Prism Scale).",getTotalPokemonCount())
pokemonObtain("Mimikyu",getBadge(),2," at the Seaport City Warehouse (after completing Home for a Hobo).",getTotalPokemonCount())
pokemonObtain("Porygon-Z",getBadge(),1," by evolving Porygon2 (Dubious Disc).",getTotalPokemonCount())
pokemonObtain("Rotom",getBadge(),2," by completing the Too Much TV mission.",getTotalPokemonCount())
achievement(
    title = "Alolan Starters I", 
    description = "Obtain either Rowlet, Litten, or Popplio from a lady in Seaport City.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Rowlet",getBadge(),getTotalPokemonCount()) ||
        obtain("Litten",getBadge(),getTotalPokemonCount()) ||
        obtain("Popplio",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Starters II", 
    description = "Evolve your Alolan starter to become either Dartrix, Torracat, or Brionne.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Dartrix",getBadge(),getTotalPokemonCount()) ||
        obtain("Torracat",getBadge(),getTotalPokemonCount()) ||
        obtain("Brionne",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Starters III", 
    description = "Evolve your Alolan starter to their final form as either Decidueye, Incineroar, or Primarina.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Decidueye",getBadge(),getTotalPokemonCount()) ||
        obtain("Incineroar",getBadge(),getTotalPokemonCount()) ||
        obtain("Primarina",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Sinnoh Starters IV", 
    description = "Obtain either Turtwig, Chimchar, or Piplup from a girl in Dehara City.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Turtwig",getBadge(),getTotalPokemonCount()) ||
        obtain("Chimchar",getBadge(),getTotalPokemonCount()) ||
        obtain("Piplup",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Sinnoh Starters V", 
    description = "Evolve your second Sinnoh starter to become either Grotle, Monferno, or Prinplup.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Grotle",getBadge(),getTotalPokemonCount()) ||
        obtain("Monferno",getBadge(),getTotalPokemonCount()) ||
        obtain("Prinplup",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Sinnoh Starters VI", 
    description = "Evolve your second Sinnoh starter to their final form as either Torterra, Infernape, or Empoleon.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Torterra",getBadge(),getTotalPokemonCount()) ||
        obtain("Infernape",getBadge(),getTotalPokemonCount()) ||
        obtain("Empoleon",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Decidueye I", description = "If possible, obtain Hisuian Decidueye by evolving Dartrix (Hisui Rock).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Decidueye",getBadge(),0x4e2,getTotalPokemonCount())) || pokedex["Litten"] == 1 || pokedex["Popplio"] == 1
    ) && badges["Swamp"] != 1
)


function getTotalPokemonCount() => 634
unlockBadge(getBadge(), "Tessy", 0x0024, getTotalPokemonCount(), " (+22, 23, or 24 variations, max 636 registered).", "at least ")
leaderboard(
    getBadge() + " Badge Speedrun",
    "Fastest in-game time to obtain the " + getBadge() + " Badge with at least " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x0024, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Badge 8

function getBadge() => "Time"

pokemonObtain("Qwilfish",getBadge(),1," by fishing with the Super Rod at Magnolia Fields or Crystal Peak.",getTotalPokemonCount())
pokemonObtain("Frillish",getBadge(),1," by surfing in Magnolia Fields.",getTotalPokemonCount())
pokemonObtain("Jellicent",getBadge(),1," by surfing in Magnolia Fields or by evolving Frillish.",getTotalPokemonCount())
pokemonObtain("Skarmory",getBadge(),1," at Crystal Peak.",getTotalPokemonCount())
pokemonObtain("Whismur",getBadge(),1," by breeding Loudred or Exploud.",getTotalPokemonCount())
pokemonObtain("Loudred",getBadge(),1," at Crystal Peak.",getTotalPokemonCount())
pokemonObtain("Exploud",getBadge(),1," by evolving Loudred.",getTotalPokemonCount())
pokemonObtain("Absol",getBadge(),1," at Crystal Peak (outside).",getTotalPokemonCount())
pokemonObtain("Drifloon",getBadge(),1," by breeding Drifblim.",getTotalPokemonCount())
pokemonObtain("Drifblim",getBadge(),1," at Crystal Peak (outside).",getTotalPokemonCount())
pokemonObtain("Dratini",getBadge(),1," by breeding Dragonair or Dragonite.",getTotalPokemonCount())
pokemonObtain("Dragonair",getBadge(),1," by surfing in Crystal Peak.",getTotalPokemonCount())
pokemonObtain("Dragonite",getBadge(),1," by evolving Dragonair.",getTotalPokemonCount())
pokemonObtain("Hoopa",getBadge(),1," from the main story.",getTotalPokemonCount())
pokemonObtain("Bonsly",getBadge(),1," by breeding Sudowoodo with a Rock Incense.",getTotalPokemonCount())
pokemonObtain("Sudowoodo",getBadge(),1," on Route 18.",getTotalPokemonCount())
pokemonObtain("Happiny",getBadge(),1," on Route 18.",getTotalPokemonCount())
pokemonObtain("Chansey",getBadge(),2," by evolving Happiny (Oval Stone).",getTotalPokemonCount())
pokemonObtain("Blissey",getBadge(),1," by evolving Chansey.",getTotalPokemonCount())
pokemonObtain("Bouffalant",getBadge(),1," on Route 18.",getTotalPokemonCount())
achievement(
    title = "Meowth", description = "Obtain Meowth by breeding Persian.", points = 1,
    trigger = (
    (
        always_false() || 
        hatch("Meowth",getBadge(),0x034,getTotalPokemonCount()))
    )
)
achievement(
    title = "Persian", description = "Obtain Persian on Route 18 (day).", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Persian",getBadge(),0x035,getTotalPokemonCount()))
    )
)
pokemonObtain("Farfetch'd",getBadge(),1," on Route 18 (day).",getTotalPokemonCount())
achievement(
    title = "Stunky", description = "Obtain Stunky by breeding Skuntank.", points = 1,
    trigger = (
    (
        always_false() || 
        hatch("Stunky",getBadge(),0x1e7,getTotalPokemonCount())) || (AreaLocation() == 0x0024 && pokedex["Stunky"] == 1 && badges["Swamp"] == 1 && OptionsCheck())
    )
)
achievement(
    title = "Skuntank", description = "Obtain Skuntank on Route 18 (night).", points = 1,
    trigger = (
    (
        always_false() || 
        catch("Skuntank",getBadge(),0x1e8,getTotalPokemonCount())) || (AreaLocation() == 0x0024 && pokedex["Skuntank"] == 1 && badges["Swamp"] == 1 && OptionsCheck())
    )
)
pokemonObtain("Chikorita",getBadge(),1," by breeding Bayleef or Meganium.",getTotalPokemonCount())
pokemonObtain("Bayleef",getBadge(),1," on Route 18 (swarm).",getTotalPokemonCount())
pokemonObtain("Meganium",getBadge(),1," by evolving Bayleef.",getTotalPokemonCount())
pokemonObtain("Litwick",getBadge(),1," by breeding Lampent or Chandelure.",getTotalPokemonCount())
pokemonObtain("Lampent",getBadge(),1," by trading a Zweilous with a guy in Redwood Village.",getTotalPokemonCount())
pokemonObtain("Chandelure",getBadge(),1," by evolving Lampent.",getTotalPokemonCount())
pokemonObtain("Heracross",getBadge(),1," in Redwood Forest or by headbutting Redwood Forest trees.",getTotalPokemonCount())
pokemonObtain("Scyther",getBadge(),1," by headbutting Redwood Forest trees.",getTotalPokemonCount())
pokemonObtain("Scizor",getBadge(),1," by evolving Scyther (Metal Coat).",getTotalPokemonCount())
pokemonObtain("Pinsir",getBadge(),1," by headbutting Redwood Forest trees.",getTotalPokemonCount())
pokemonObtain("Aipom",getBadge(),1," by headbutting Redwood Forest trees.",getTotalPokemonCount())
pokemonObtain("Ambipom",getBadge(),1," by evolving Aipom (level-Up while knowing Double Hit).",getTotalPokemonCount())
pokemonObtain("Pineco",getBadge(),1," by headbutting Redwood Forest trees.",getTotalPokemonCount())
pokemonObtain("Forretress",getBadge(),1," by evolving Pineco.",getTotalPokemonCount())
achievement(
    title = "Alolan Starters IV", 
    description = "Obtain either Rowlet, Litten, or Popplio from a lady in Seaport City.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Rowlet",getBadge(),getTotalPokemonCount()) ||
        obtain("Litten",getBadge(),getTotalPokemonCount()) ||
        obtain("Popplio",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Starters V", 
    description = "Evolve your second Alolan starter to become either Dartrix, Torracat, or Brionne.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Dartrix",getBadge(),getTotalPokemonCount()) ||
        obtain("Torracat",getBadge(),getTotalPokemonCount()) ||
        obtain("Brionne",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Starters VI", 
    description = "Evolve your second Alolan starter to their final form as either Decidueye, Incineroar, or Primarina.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Decidueye",getBadge(),getTotalPokemonCount()) ||
        obtain("Incineroar",getBadge(),getTotalPokemonCount()) ||
        obtain("Primarina",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Unova Starters VII", 
    description = "Obtain either Snivy, Tepig, or Oshawott from a girl on Route 5.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Snivy",getBadge(),getTotalPokemonCount()) ||
        obtain("Tepig",getBadge(),getTotalPokemonCount()) ||
        obtain("Oshawott",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Unova Starters VIII", 
    description = "Evolve your third and final Unova starter to become either Servine, Pignite, or Dewott.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Servine",getBadge(),getTotalPokemonCount()) ||
        obtain("Pignite",getBadge(),getTotalPokemonCount()) ||
        obtain("Dewott",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Unova Starters IX", 
    description = "Evolve your third and final Unova starter to their final form as either Serperior, Emboar, or Samurott.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Serperior",getBadge(),getTotalPokemonCount()) ||
        obtain("Emboar",getBadge(),getTotalPokemonCount()) ||
        obtain("Samurott",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Decidueye II", description = "If possible, obtain Hisuian Decidueye by evolving Dartrix (Hisui Rock).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Decidueye",getBadge(),0x4e2,getTotalPokemonCount())) || pokedex["Litten"] == 1 && pokedex["Popplio"] == 1
    )
)
achievement(
    title = "Hisuian Samurott III", description = "If not already obtained, obtain Hisuian Samurott by evolving Dewott (Hisui Rock).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Samurott",getBadge(),0x4d9,getTotalPokemonCount()) || (pokedex["Samurott"] == 1 && badges["Swamp"] > prev(badges["Swamp"]) && AreaLocation() == 0x0024))
    ) && badges["Time"] != 1
)


function getTotalPokemonCount() => 677
unlockBadge(getBadge(), "Benjamin", 0x0204, getTotalPokemonCount(), " (+25 or 26 variations).")
leaderboard(
    getBadge() + " Badge Speedrun",
    "Fastest in-game time to obtain the " + getBadge() + " Badge with all " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x0204, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Pokemon League

function getBadge() => "Pokemon League"

pokemonObtain("Rhyperior",getBadge(),1," by evolving Rhydon (hidden Protector).",getTotalPokemonCount())
pokemonObtain("Igglybuff",getBadge(),1," by breeding Jigglypuff.",getTotalPokemonCount())
pokemonObtain("Jigglypuff",getBadge(),1," on Victory Road.",getTotalPokemonCount())
pokemonObtain("Wigglytuff",getBadge(),1," by evolving Jigglypuff (Moon Stone).",getTotalPokemonCount())
pokemonObtain("Druddigon",getBadge(),1," on Victory Road.",getTotalPokemonCount())
pokemonObtain("Durant",getBadge(),1," on Victory Road.",getTotalPokemonCount())
pokemonObtain("Fomantis",getBadge(),1," by breeding Lurantis.",getTotalPokemonCount())
pokemonObtain("Lurantis",getBadge(),1," on Victory Road.",getTotalPokemonCount())
pokemonObtain("Turtonator",getBadge(),1," on Victory Road.",getTotalPokemonCount())
pokemonObtain("Drampa",getBadge(),1," on Victory Road.",getTotalPokemonCount())
pokemonObtain("Jangmo-o",getBadge(),1," by breeding Hakamo-o.",getTotalPokemonCount())
pokemonObtain("Hakamo-o",getBadge(),1," on Victory Road.",getTotalPokemonCount())
pokemonObtain("Kommo-o",getBadge(),1," by evolving Hakamo-o.",getTotalPokemonCount())
achievement(
    title = "Alolan Starters VII", 
    description = "Obtain either Rowlet, Litten, or Popplio from a lady in Seaport City.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Rowlet",getBadge(),getTotalPokemonCount()) ||
        obtain("Litten",getBadge(),getTotalPokemonCount()) ||
        obtain("Popplio",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Starters VIII", 
    description = "Evolve your third and final Alolan starter to become either Dartrix, Torracat, or Brionne.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Dartrix",getBadge(),getTotalPokemonCount()) ||
        obtain("Torracat",getBadge(),getTotalPokemonCount()) ||
        obtain("Brionne",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Alolan Starters IX", 
    description = "Evolve your third and final Alolan starter to their final form as either Decidueye, Incineroar, or Primarina.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Decidueye",getBadge(),getTotalPokemonCount()) ||
        obtain("Incineroar",getBadge(),getTotalPokemonCount()) ||
        obtain("Primarina",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Hisuian Decidueye III", description = "If not already obtained, obtain Hisuian Decidueye by evolving Dewott (Hisui Rock).", points = 1,
    trigger = (
    (
        always_false() || 
        evolve("Hisian Decidueye",getBadge(),0x4e2,getTotalPokemonCount()) || (pokedex["Decidueye"] == 1 && badges["Time"] > prev(badges["Time"])))
    )
)
achievement(
    title = "Sinnoh Starters VII", 
    description = "Obtain either Turtwig, Chimchar, or Piplup from a girl in Dehara City.", 
    points = 1,
    trigger = (
    (
        always_false() ||
        obtain("Turtwig",getBadge(),getTotalPokemonCount()) ||
        obtain("Chimchar",getBadge(),getTotalPokemonCount()) ||
        obtain("Piplup",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Sinnoh Starters VIII", 
    description = "Evolve your third and final Sinnoh starter to become either Grotle, Monferno, or Prinplup.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Grotle",getBadge(),getTotalPokemonCount()) ||
        obtain("Monferno",getBadge(),getTotalPokemonCount()) ||
        obtain("Prinplup",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Sinnoh Starters IX", 
    description = "Evolve your third and final Sinnoh starter to their final form as either Torterra, Infernape, or Empoleon.", 
    points = 1,
    trigger = (
    (
        always_false() || 
        obtain("Torterra",getBadge(),getTotalPokemonCount()) ||
        obtain("Infernape",getBadge(),getTotalPokemonCount()) ||
        obtain("Empoleon",getBadge(),getTotalPokemonCount()))
    )
)
achievement(
    title = "Eon Duo I", description = "Obtain your gender-specific member of the Eon Duo by completing 45 missions.", points = 2,
    trigger = (
    (
        (byte(0x2c590) == 0x00 && obtain("Latios",getBadge(),getTotalPokemonCount())) || (byte(0x2c590) == 0x01 && obtain("Latias",getBadge(),getTotalPokemonCount()))
    ))
)

function getTotalPokemonCount() => 697
achievement(
        title = "Pokemon League", 
        description = "Defeat the Pokemon League and become the new Pokemon Champion with all " + getTotalPokemonCount() + " Pokemon registered in the National Dex (+26 variations)",
        points = 10,
        trigger = (
           measured(CaughtPokemonAmount() == getTotalPokemonCount(), always_true(), format="raw") && AreaLocation() == 0x00da && badges[getBadge()] > prev(badges[getBadge()]) && OptionsCheck()
        )
)
leaderboard(
    getBadge() + " Speedrun",
    "Fastest in-game time to beat the Pokemon League with all " + getTotalPokemonCount() + " Pokemon obtained!",
    startLeaderboard(getBadge(), 0x00da, getTotalPokemonCount()),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)

// Postgame

function getBadge() => "Postgame"

pokemonObtain("Carbink",getBadge(),1," by mining a collapsed doorway with the ADM.",getTotalPokemonCount())
pokemonObtain("Clamperl",getBadge(),1," underwater (on Routes 14, 16, 17, at the Ruins of Void).",getTotalPokemonCount())
pokemonObtain("Huntail",getBadge(),1," by evolving Clamperl by using a Deep Sea Tooth.",getTotalPokemonCount())
pokemonObtain("Gorebyss",getBadge(),1," by evolving Clamperl by using a Deep Sea Scale.",getTotalPokemonCount())
pokemonObtain("Mareanie",getBadge(),1," underwater (on Route 14 or at the Ruins of Void).",getTotalPokemonCount())
pokemonObtain("Toxapex",getBadge(),1," underwater (on Route 14 or at the Ruins of Void) or by evolving Mareanie.",getTotalPokemonCount())
pokemonObtain("Relicanth",getBadge(),1," underwater at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Teddiursa",getBadge(),1," by breeding Ursaring.",getTotalPokemonCount())
pokemonObtain("Ursaring",getBadge(),1," in Redwood Forest.",getTotalPokemonCount())
pokemonObtain("Slakoth",getBadge(),1," by breeding Vigorith or Slaking.",getTotalPokemonCount())
pokemonObtain("Vigoroth",getBadge(),1," in Redwood Forest.",getTotalPokemonCount())
pokemonObtain("Slaking",getBadge(),1," by evolving Vigorith.",getTotalPokemonCount())
pokemonObtain("Oranguru",getBadge(),1," in Redwood Forest.",getTotalPokemonCount())
pokemonObtain("Passimian",getBadge(),1," in Redwood Forest.",getTotalPokemonCount())
pokemonObtain("Komala",getBadge(),1," in Redwood Forest.",getTotalPokemonCount())
pokemonObtain("Zorua",getBadge(),1," by breeding Zoroark.",getTotalPokemonCount())
pokemonObtain("Zoroark",getBadge(),1," in Redwood Forest (static - after chasing).",getTotalPokemonCount())
pokemonObtain("Munchlax",getBadge(),1," by breeding Snorlax with a Full Incense.",getTotalPokemonCount())
pokemonObtain("Snorlax",getBadge(),1," in Redwood Forest (static).",getTotalPokemonCount())
pokemonObtain("Nincada",getBadge(),1," in Redwood Forest (swarm).",getTotalPokemonCount())
pokemonObtain("Ninjask",getBadge(),1," by evolving Nincada.",getTotalPokemonCount())
pokemonObtain("Shedinja",getBadge(),1," by evolving Ninjask.",getTotalPokemonCount())
pokemonObtain("Froakie",getBadge(),1," as an egg randomly from the Magnolia Café Egg Lady.",getTotalPokemonCount())
pokemonObtain("Frogadier",getBadge(),1," by evolving Froakie.",getTotalPokemonCount())
pokemonObtain("Greninja",getBadge(),1," by evolving Frogadier.",getTotalPokemonCount())
pokemonObtain("Larvesta",getBadge(),2," as a reward for completing The Treasure Hunter mission.",getTotalPokemonCount())
pokemonObtain("Volcarona",getBadge(),1," by evolving Larvesta.",getTotalPokemonCount())
pokemonObtain("Spiritomb",getBadge(),2," by talking to an old lady in the Gurun Town PC with an Odd Keystone in your Cube.",getTotalPokemonCount())
pokemonObtain("Unown",getBadge(),1," in the Tomb of Borrius.",getTotalPokemonCount())
pokemonObtain("Castform",getBadge(),2," from a clown in Seaport Boathouse after obtaining all of the weather TMs and the Defog TM.",getTotalPokemonCount())

// Other starters
achievement(
    title = "Rival's Starter I", description = "Obtain the starter that your rival chose.", points = 1,
    trigger = (
    (
       always_false() || 
       (obtain("Larvitar",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x01) ||
       (obtain("Beldum",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x02) ||
       (obtain("Gible",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x03))
    )
)
achievement(
    title = "Rival's Starter II", description = "Evolve the starter that your rival chose.", points = 1,
    trigger = (
    (
       always_false() || 
       (obtain("Pupitar",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x01) ||
       (obtain("Metang",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x02) ||
       (obtain("Gabite",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x03))
    )
)
achievement(
    title = "Rival's Starter III", description = "Evolve the starter that your rival chose to their final form.", points = 1,
    trigger = (
    (
       always_false() || 
       (obtain("Tyranitar",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x01) ||
       (obtain("Metagross",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x02) ||
       (obtain("Garchomp",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x03))
    )
)
achievement(
    title = "Lonely Starter I", description = "Obtain the starter that no one chose.", points = 1,
    trigger = (
    (
       always_false() || 
       (obtain("Larvitar",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x03) ||
       (obtain("Beldum",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x01) ||
       (obtain("Gible",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x02))
    )
)
achievement(
    title = "Lonely Starter II", description = "Evolve the starter that no one chose.", points = 1,
    trigger = (
    (
       always_false() || 
       (obtain("Pupitar",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x03) ||
       (obtain("Metang",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x01) ||
       (obtain("Gabite",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x02))
    )
)
achievement(
    title = "Lonely Starter III", description = "Evolve the starter that no one chose to their final form.", points = 1,
    trigger = (
    (
       always_false() || 
       (obtain("Tyranitar",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x03) ||
       (obtain("Metagross",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x01) ||
       (obtain("Garchomp",getBadge(),getTotalPokemonCount()) && StarterChoice() == 0x02))
    )
)

// Legendaries
achievement(
    title = "Eon Duo II", description = "Obtain the other member of the Eon Duo by completing the No Survivors mission, then going to the Pokémon League with the other member of the Eon Duo in your party.", points = 1,
    trigger = (
    (
        (byte(0x2c590) == 0x01 && obtain("Latios",getBadge(),getTotalPokemonCount())) || (byte(0x2c590) == 0x00 && obtain("Latias",getBadge(),getTotalPokemonCount()))
    ))
)
pokemonObtain("Mew",getBadge(),2," as a reward for completing the Darwin Was Right mission.",getTotalPokemonCount())
pokemonObtain("Articuno",getBadge(),1," by going North of Frozen Heights.",getTotalPokemonCount())
pokemonObtain("Zapdos",getBadge(),1," on top of Thundercap Mountain.",getTotalPokemonCount())
pokemonObtain("Moltres",getBadge(),1," on top of Cinder Volcano.",getTotalPokemonCount())
pokemonObtain("Celebi",getBadge(),1," at Redwood Village, with a Spiky-Eared Pichu in your party.",getTotalPokemonCount())
pokemonObtain("Raikou",getBadge(),1," at the Ruins of Void (Roaming).",getTotalPokemonCount())
pokemonObtain("Entei",getBadge(),1," at the Ruins of Void (Roaming).",getTotalPokemonCount())
pokemonObtain("Suicune",getBadge(),1," from a Portal at the Ruins of Void, with Raikou and Entei in your party.",getTotalPokemonCount())
pokemonObtain("Lugia",getBadge(),1," from a Portal at the Ruins of Void, with Raikou, Entei, and Suicune in your party.",getTotalPokemonCount())
pokemonObtain("Ho-Oh",getBadge(),1," from a Portal at the Ruins of Void, with Raikou, Entei, and Suicune in your party.",getTotalPokemonCount())
pokemonObtain("Jirachi",getBadge(),1," at a locked house in Crater Town.",getTotalPokemonCount())
pokemonObtain("Deoxys",getBadge(),1," on Route 5 to on Route 13 path, with Jirachi in your party.",getTotalPokemonCount())
pokemonObtain("Regirock",getBadge(),1," in the Desert Ruins, with the Tomb Raider mission completed.",getTotalPokemonCount())
pokemonObtain("Regice",getBadge(),1," in the Frozen Cave, with the Tomb Raider mission completed.",getTotalPokemonCount())
pokemonObtain("Registeel",getBadge(),1," in the Ancient Tomb, with the Tomb Raider mission completed.",getTotalPokemonCount())
pokemonObtain("Regigigas",getBadge(),1," at Icy Hole, with Regirock, Regice, and Registeel in the first 3 slots of your party.",getTotalPokemonCount())
pokemonObtain("Kyogre",getBadge(),1," by bringing the Blue Orb to Vivill Warehouse (Underwater).",getTotalPokemonCount())
pokemonObtain("Groudon",getBadge(),1," by bringing the Red Orb to the Cinder Volcano Shadow Basement.",getTotalPokemonCount())
pokemonObtain("Rayquaza",getBadge(),1," by bringing the Jade Orb to the summit of Crystal Peak.",getTotalPokemonCount())
pokemonObtain("Uxie",getBadge(),1," in front of Dream Research Lab with the Guardians of the Lake mission activated.",getTotalPokemonCount())
pokemonObtain("Mesprit",getBadge(),1," in the Shadow Base with the Guardians of the Lake mission activated.",getTotalPokemonCount())
pokemonObtain("Azelf",getBadge(),1," above the Pokémon Center on on Route 18 with the Guardians of the Lake mission activated.",getTotalPokemonCount())
pokemonObtain("Heatran",getBadge(),1," in Cinder Volcano after obtaining the Magma Stone.",getTotalPokemonCount())
pokemonObtain("Dialga",getBadge(),1," at the Cave of Being with the Lake guardians in your party.",getTotalPokemonCount())
pokemonObtain("Palkia",getBadge(),1," at the Rift Cave with the Rift in Space mission activated.",getTotalPokemonCount())
pokemonObtain("Giratina",getBadge(),1," in the Distortion World.",getTotalPokemonCount())
pokemonObtain("Darkrai",getBadge(),1," at Newmoon Island after completing The Endless Nightmare.",getTotalPokemonCount())
pokemonObtain("Shaymin",getBadge(),1," in Flower Paradise.",getTotalPokemonCount())
pokemonObtain("Arceus",getBadge(),2," by talking to the scientist in Dream Research Lab after obtaining all 17 Plates.",getTotalPokemonCount())
pokemonObtain("Cobalion",getBadge(),1," at the Victory Road Snowy Area, with the Swords of Justice mission activated.",getTotalPokemonCount())
pokemonObtain("Terrakion",getBadge(),1," at Victory Road 3F, with the Swords of Justice mission activated.",getTotalPokemonCount())
pokemonObtain("Virizion",getBadge(),1," at the Victory Road Grassy Maze Area, with the Swords of Justice mission activated.",getTotalPokemonCount())
pokemonObtain("Keldeo",getBadge(),1," on Route 17 with Cobalion, Terrakion, and Virizion in your party.",getTotalPokemonCount())
pokemonObtain("Tornadus",getBadge(),1," at Magnolia Fields (roaming).",getTotalPokemonCount())
pokemonObtain("Thundurus",getBadge(),1," at Magnolia Fields (roaming).",getTotalPokemonCount())
pokemonObtain("Landorus",getBadge(),1," at Magnolia Fields with Tornadus and Thundurus in your party.",getTotalPokemonCount())
pokemonObtain("Reshiram",getBadge(),1," from a Portal in Crystal Peak 3F (day).",getTotalPokemonCount())
pokemonObtain("Zekrom",getBadge(),1," from a Portal in Crystal Peak 3F (night).",getTotalPokemonCount())
pokemonObtain("Kyurem",getBadge(),1," at Victory Road (inside a cave in the Snowy Area).",getTotalPokemonCount())
pokemonObtain("Victini",getBadge(),2," as a reward for completing the Gimme a V mission.",getTotalPokemonCount())
pokemonObtain("Meloetta",getBadge(),1," at Polder Town (night).",getTotalPokemonCount())
pokemonObtain("Xerneas",getBadge(),1," from Portal in Redwood Forest (day).",getTotalPokemonCount())
pokemonObtain("Yveltal",getBadge(),1," from Portal in Crystal Peak (night).",getTotalPokemonCount())
pokemonObtain("Diancie",getBadge(),1," behind any collapsed doorway in the in the KBT Expressway, after completing the Major Miner mission.",getTotalPokemonCount())
pokemonObtain("Volcanion",getBadge(),2," in Cinder Volcano (after re-beating the E4).",getTotalPokemonCount())
pokemonObtain("Tapu Koko",getBadge(),1," from a Portal outside of Cliff Cave.",getTotalPokemonCount())
pokemonObtain("Tapu Lele",getBadge(),1," from a Portal on Route 17.",getTotalPokemonCount())
pokemonObtain("Tapu Bulu",getBadge(),1," from a Portal on Route 9.",getTotalPokemonCount())
pokemonObtain("Tapu Fini",getBadge(),1," from a Portal on Route 2.",getTotalPokemonCount())
pokemonObtain("Cosmog",getBadge(),1," from a bag on the beach on Route 12.",getTotalPokemonCount())
pokemonObtain("Cosmoem",getBadge(),1," by evolving Cosmog.",getTotalPokemonCount())
pokemonObtain("Solgaleo",getBadge(),1," by evolving Cosmoem (day) or from a portal on Route 12 during the day if Lunala is in your party.",getTotalPokemonCount())
pokemonObtain("Lunala",getBadge(),1," by evolving Cosmoem (night) or from a portal on Route 12 during the night if Solgaleo is in your party.",getTotalPokemonCount())
pokemonObtain("Zeraora",getBadge(),1," at Thundercap Mountain 4F (the ADM is required).",getTotalPokemonCount())
pokemonObtain("Magearna",getBadge(),2," at the Tomb of Borrius after completing The National Pokedex mission.",getTotalPokemonCount())
pokemonObtain("Phione",getBadge(),1," by breeding Manaphy.",getTotalPokemonCount())
pokemonObtain("Manaphy",getBadge(),2," by solving the underwater Braille tablet at the Ruins of Void.",getTotalPokemonCount())
pokemonObtain("Cresselia",getBadge(),1," on Fullmoon Island (roaming) or during The Endless Nightmare.",getTotalPokemonCount())
pokemonObtain("Nihilego",getBadge(),1," from a Portal beneath Route 14 (night).",getTotalPokemonCount())
pokemonObtain("Buzzwole",getBadge(),1," from a Portal above Cinder Volcano (day).",getTotalPokemonCount())
pokemonObtain("Pheromosa",getBadge(),1," from a Portal in the Great Desert (day).",getTotalPokemonCount())
pokemonObtain("Xurkitree",getBadge(),1," from a Portal in Thundercap Mountain (night).",getTotalPokemonCount())
pokemonObtain("Celesteela",getBadge(),1," from a Portal in Crater Town (night).",getTotalPokemonCount())
pokemonObtain("Kartana",getBadge(),1," from a Portal in Vivill Woods (day).",getTotalPokemonCount())
pokemonObtain("Guzzlord",getBadge(),1," from a Portal in the Antisis Sewers (night).",getTotalPokemonCount())
pokemonObtain("Necrozma",getBadge(),1," from a Portal in Frost Mountain (night) with Solgaleo and Lunala in your party.",getTotalPokemonCount())
pokemonObtain("Stakataka",getBadge(),1," from a Portal on Route 7 (day).",getTotalPokemonCount())
pokemonObtain("Blacephalon",getBadge(),1," from a Portal in Magnolia Fields (night).",getTotalPokemonCount())

function getTotalPokemonCount() => 802
//achievement(
//        title = "Professor Oak Challenge Complete!", 
//        description = "Finish the Professor Oak Challenge with " + getTotalPokemonCount() + " Pokemon registered in the National Dex, and having caught all 26 available variations!",
//        points = 10,
//        trigger = (
//           measured(CaughtPokemonAmount() == getTotalPokemonCount(), always_true(), format="raw") && OptionsCheck() 
//           && pokedex["Mewtwo"] != 1 && pokedex["Genesect"] != 1 && pokedex["Marshadow"] != 1
//           && pokedex["Poipole"] != 1 && pokedex["Naganadel"] != 1 && pokedex["Meltan"] != 1
//           && pokedex["Melmetal"] != 1 && prev(CaughtPokemonAmount()) != getTotalPokemonCount()
//        )
//)
leaderboard(
    "Full Game Professor Oak Challenge Speedrun",
    "Fastest in-game time to complete the Professor Oak Challenge with all " + getTotalPokemonCount() + " Pokemon obtained!",
    CaughtPokemonAmount() == getTotalPokemonCount() && prev(CaughtPokemonAmount()) != getTotalPokemonCount() && OptionsCheck(),
    always_false(),
    always_true(),
    InGameTimerSeconds(),
    format = "SECS",
    lower_is_better = true
)